/* Outside Of Time: the quote bank for Lizzy, the Maitre d'.
   GENERATED by WorldTable/tools/quotes/build-quotes.mjs from tools/quotes/candidates.json; 67 entries, bank dated 2026-10-03; do not edit; regenerate with node tools/quotes/build-quotes.mjs.

   WHAT THIS IS. The only quotations the Maitre d' may put in anyone's mouth,
   each one placed in a named work by a named author and checked by a
   person before it was ticked to ship. The client hands her this list by
   id and refuses any quoted span of hers that is not in it, so a line she
   cannot source is a line she does not say. Every entry carries the words,
   the author, the work, the year, its tags and whether the wording was
   adapted (a dash made a comma, a sentence cut) to fit; the source, the
   evidence and the doubts stay in candidates.json, which never ships, and
   no address of any kind is written here.

   Classic script, no build step, no dependency: one IIFE that installs
   window.OOT.quotes = { v, builtOn, quotes } and returns at once when it is
   already there. It touches no DOM and makes no request, so it can be
   loaded by any wing at any time; the client reads OOT.quotes when it is
   called and never fetches it. Loaded lazily and not precached, like the
   client. Pure ASCII: every letter outside ASCII is a \uXXXX escape, so the
   site's publish gate, which counts dashes across the tree, reads none.

   Canonical source: WorldTable/static/shared/oot-quotes.js, mirrored byte
   for byte to the site's shared/oot-quotes.js; the site's check-mirror
   fails on drift rather than overwrite. tools/quotes/check-quotes.mjs
   proves this file against candidates.json and the closed list of names.
*/
(function (w) {
  'use strict';
  var OOT = w.OOT = w.OOT || {};
  if (OOT.quotes) return; // loaded twice by two doors: the first install stands
  OOT.quotes = {
    v: 1,
    builtOn: "2026-10-03",
    quotes: [
      {
        id: "q-ab01",
        text: "Good food is very often, even most often, simple food.",
        who: "Anthony Bourdain",
        work: "Kitchen Confidential",
        year: "2000",
        tags: ["kitchen", "craft"],
        adapted: false
      },
      {
        id: "q-ab02",
        text: "Cooking is a craft, I like to think, and a good cook is a craftsman, not an artist.",
        who: "Anthony Bourdain",
        work: "Kitchen Confidential",
        year: "2000",
        tags: ["kitchen", "craft", "work"],
        adapted: true
      },
      {
        id: "q-bd01",
        text: "The proper union of gin and vermouth is a great and sudden glory; it is one of the happiest marriages on earth, and one of the shortest-lived.",
        who: "Bernard DeVoto",
        work: "The Hour",
        year: "1948",
        tags: ["bar", "pleasure"],
        adapted: false
      },
      {
        id: "q-bs04",
        text: "Tell me what you eat, and I shall tell you what you are.",
        who: "Jean Anthelme Brillat-Savarin",
        work: "The Physiology of Taste",
        year: "1825",
        tags: ["table", "character", "pleasure"],
        adapted: false
      },
      {
        id: "q-bs05",
        text: "The Creator, in obliging man to eat in order to live, invites him by appetite and rewards him by pleasure.",
        who: "Jean Anthelme Brillat-Savarin",
        work: "The Physiology of Taste",
        year: "1825",
        tags: ["pleasure", "hunger", "table"],
        adapted: false
      },
      {
        id: "q-bs07",
        text: "The pleasure of the table belongs to all ages, to all conditions, to all countries and to all days; it can be joined to all other pleasures, and remains the last to console us for their loss.",
        who: "Jean Anthelme Brillat-Savarin",
        work: "The Physiology of Taste",
        year: "1825",
        tags: ["table", "pleasure", "hospitality"],
        adapted: false
      },
      {
        id: "q-bs09",
        text: "The discovery of a new dish does more for the happiness of mankind than the discovery of a star.",
        who: "Jean Anthelme Brillat-Savarin",
        work: "The Physiology of Taste",
        year: "1825",
        tags: ["kitchen", "craft", "pleasure"],
        adapted: false
      },
      {
        id: "q-bs10",
        text: "Those who get indigestion or who get drunk do not know how to eat or to drink.",
        who: "Jean Anthelme Brillat-Savarin",
        work: "The Physiology of Taste",
        year: "1825",
        tags: ["table", "wine", "discipline"],
        adapted: false
      },
      {
        id: "q-bs20",
        text: "To invite someone is to take charge of his happiness for as long as he is under our roof.",
        who: "Jean Anthelme Brillat-Savarin",
        work: "The Physiology of Taste",
        year: "1825",
        tags: ["hospitality", "generosity", "table"],
        adapted: false
      },
      {
        id: "q-cb01",
        text: "One should always be drunk. That is all there is to it: it is the only question. But with what? With wine, with poetry, or with virtue, as you choose. But get drunk.",
        who: "Charles Baudelaire",
        work: "Paris Spleen",
        year: "1869",
        tags: ["wine", "pleasure", "time"],
        adapted: true
      },
      {
        id: "q-cb02",
        text: "One evening, the soul of wine sang in the bottles.",
        who: "Charles Baudelaire",
        work: "The Flowers of Evil",
        year: "1857",
        tags: ["wine"],
        adapted: false
      },
      {
        id: "q-cf01",
        text: "When you know a thing, to hold that you know it; and when you do not know a thing, to allow that you do not know it; this is knowledge.",
        who: "Confucius",
        work: "Analects",
        year: "c. 450 BC",
        tags: ["honesty", "discipline"],
        adapted: true
      },
      {
        id: "q-cf02",
        text: "Is it not delightful to have friends coming from distant quarters?",
        who: "Confucius",
        work: "Analects",
        year: "c. 450 BC",
        tags: ["hospitality", "travel", "generosity"],
        adapted: false
      },
      {
        id: "q-cf03",
        text: "He did not eat anything which was ill-cooked, or was not in season. He did not eat meat which was not cut properly, nor what was served without its proper sauce.",
        who: "Confucius",
        work: "Analects",
        year: "c. 450 BC",
        tags: ["kitchen", "craft", "discipline"],
        adapted: true
      },
      {
        id: "q-ec01",
        text: "No great thing is created suddenly, any more than a bunch of grapes or a fig. Let it first blossom, then bear fruit, then ripen.",
        who: "Epictetus",
        work: "Discourses",
        year: "c. 108",
        tags: ["patience", "craft", "wine"],
        adapted: true
      },
      {
        id: "q-ed01",
        text: "Good food is always a trouble and its preparation should be regarded as a labour of love.",
        who: "Elizabeth David",
        work: "French Country Cooking",
        year: "1951",
        tags: ["kitchen", "craft", "work"],
        adapted: false
      },
      {
        id: "q-eh01",
        text: "If you are lucky enough to have lived in Paris as a young man, then wherever you go for the rest of your life, it stays with you, for Paris is a moveable feast.",
        who: "Ernest Hemingway",
        work: "A Moveable Feast",
        year: "1964",
        tags: ["travel", "pleasure", "memory"],
        adapted: false
      },
      {
        id: "q-eh02",
        text: "Wine is one of the most civilized things in the world and one of the most natural things of the world that has been brought to the greatest perfection.",
        who: "Ernest Hemingway",
        work: "Death in the Afternoon",
        year: "1932",
        tags: ["wine", "pleasure", "craft"],
        adapted: true
      },
      {
        id: "q-eh03",
        text: "As I ate the oysters with their strong taste of the sea and their faint metallic taste that the cold white wine washed away, leaving only the sea taste and the succulent texture.",
        who: "Ernest Hemingway",
        work: "A Moveable Feast",
        year: "1964",
        tags: ["table", "wine", "hunger", "pleasure"],
        adapted: true
      },
      {
        id: "q-ep01",
        text: "Of all the things which wisdom provides to make life entirely happy, much the greatest is the possession of friendship.",
        who: "Epicurus",
        work: "Principal Doctrines",
        year: "c. 300 BC",
        tags: ["generosity", "friendship", "pleasure"],
        adapted: false
      },
      {
        id: "q-ep02",
        text: "Reflect carefully with whom you are to eat and drink, rather than what you are to eat and drink; for a dinner of meats without the company of a friend is like the life of a lion or a wolf.",
        who: "Epicurus",
        work: "as quoted by Seneca, Letters to Lucilius",
        year: "c. 64",
        tags: ["table", "hospitality", "generosity"],
        adapted: true
      },
      {
        id: "q-ep03",
        text: "Plain fare gives as much pleasure as a costly diet, when once the pain of want has been removed.",
        who: "Epicurus",
        work: "Letter to Menoeceus",
        year: "c. 300 BC",
        tags: ["hunger", "pleasure", "table"],
        adapted: false
      },
      {
        id: "q-gs01",
        text: "There is no love sincerer than the love of food.",
        who: "George Bernard Shaw",
        work: "Man and Superman",
        year: "1903",
        tags: ["table", "pleasure"],
        adapted: false
      },
      {
        id: "q-hc01",
        text: "Shake the shaker as hard as you can: don't just rock it, you are trying to wake it up, not send it to sleep!",
        who: "Harry Craddock",
        work: "The Savoy Cocktail Book",
        year: "1930",
        tags: ["bar", "craft"],
        adapted: true
      },
      {
        id: "q-hdt1",
        text: "I went to the woods because I wished to live deliberately, to front only the essential facts of life, and see if I could not learn what it had to teach.",
        who: "Henry David Thoreau",
        work: "Walden",
        year: "1854",
        tags: ["discipline", "honesty"],
        adapted: true
      },
      {
        id: "q-hdt2",
        text: "The cost of a thing is the amount of what I will call life which is required to be exchanged for it, immediately or in the long run.",
        who: "Henry David Thoreau",
        work: "Walden",
        year: "1854",
        tags: ["work", "discipline"],
        adapted: false
      },
      {
        id: "q-hr01",
        text: "Seize the day, trusting as little as possible in the next.",
        who: "Horace",
        work: "Odes",
        year: "23 BC",
        tags: ["pleasure", "time"],
        adapted: false
      },
      {
        id: "q-hr02",
        text: "Now is the time for drinking, now the time to beat the earth with unfettered foot.",
        who: "Horace",
        work: "Odes",
        year: "23 BC",
        tags: ["wine", "bar", "pleasure"],
        adapted: false
      },
      {
        id: "q-hr03",
        text: "They change their sky, not their soul, who run across the sea.",
        who: "Horace",
        work: "Epistles",
        year: "20 BC",
        tags: ["travel"],
        adapted: false
      },
      {
        id: "q-hr04",
        text: "Life grants nothing to mortals without great labour.",
        who: "Horace",
        work: "Satires",
        year: "35 BC",
        tags: ["work", "craft", "discipline"],
        adapted: false
      },
      {
        id: "q-jb01",
        text: "Food is our common ground, a universal experience.",
        who: "James Beard",
        work: "Beard on Food",
        year: "1974",
        tags: ["table", "hospitality"],
        adapted: false
      },
      {
        id: "q-jc01",
        text: "This is a book for the servantless American cook who can be unconcerned on occasion with budgets, waistlines, time tables, children's meals, the parent-chauffeur-den-mother syndrome, or anything else which might interfere with the enjoyment of producing something wonderful to eat.",
        who: "Julia Child",
        work: "Mastering the Art of French Cooking",
        year: "1961",
        tags: ["kitchen", "pleasure", "craft"],
        adapted: false
      },
      {
        id: "q-jc02",
        text: "Learn how to cook, try new recipes, learn from your mistakes, be fearless, and above all have fun!",
        who: "Julia Child",
        work: "My Life in France",
        year: "2006",
        tags: ["kitchen", "fear", "craft"],
        adapted: true
      },
      {
        id: "q-jm01",
        text: "One must eat to live, and not live to eat.",
        who: "Moli\u00e8re",
        work: "The Miser",
        year: "1668",
        tags: ["table", "discipline"],
        adapted: false
      },
      {
        id: "q-js01",
        text: "He was a bold man that first eat an oyster.",
        who: "Jonathan Swift",
        work: "Polite Conversation",
        year: "1738",
        tags: ["table", "courage"],
        adapted: false
      },
      {
        id: "q-jt01",
        text: "In all ages of the world, and in all countries, men have indulged in social drinks.",
        who: "Jerry Thomas",
        work: "How to Mix Drinks, or The Bon-Vivant's Companion",
        year: "1862",
        tags: ["bar", "history"],
        adapted: true
      },
      {
        id: "q-lt01",
        text: "Governing a great state is like cooking small fish.",
        who: "Lao Tzu",
        work: "Tao Te Ching",
        year: "c. 400 BC",
        tags: ["kitchen", "patience", "craft"],
        adapted: false
      },
      {
        id: "q-lt02",
        text: "The journey of a thousand li commenced with a single step.",
        who: "Lao Tzu",
        work: "Tao Te Ching",
        year: "c. 400 BC",
        tags: ["patience", "travel", "work"],
        adapted: false
      },
      {
        id: "q-ma01",
        text: "In the morning when thou risest unwillingly, let this thought be present: I am rising to the work of a human being.",
        who: "Marcus Aurelius",
        work: "Meditations",
        year: "c. 170",
        tags: ["work", "discipline"],
        adapted: true
      },
      {
        id: "q-mc01",
        text: "Hunger is the best sauce in the world.",
        who: "Miguel de Cervantes",
        work: "Don Quixote",
        year: "1615",
        tags: ["hunger", "table"],
        adapted: false
      },
      {
        id: "q-mf01",
        text: "It seems to me that our three basic needs, for food and security and love, are so mixed and mingled and entwined that we cannot straightly think of one without the others.",
        who: "M. F. K. Fisher",
        work: "The Gastronomical Me",
        year: "1943",
        tags: ["hunger", "table", "generosity"],
        adapted: false
      },
      {
        id: "q-mf02",
        text: "There is a communion of more than our bodies when bread is broken and wine drunk.",
        who: "M. F. K. Fisher",
        work: "The Gastronomical Me",
        year: "1943",
        tags: ["table", "wine", "hospitality"],
        adapted: false
      },
      {
        id: "q-mm01",
        text: "When I dance, I dance; when I sleep, I sleep.",
        who: "Michel de Montaigne",
        work: "Essays",
        year: "1588",
        tags: ["pleasure", "discipline", "presence"],
        adapted: false
      },
      {
        id: "q-mm02",
        text: "The thing I fear most is fear.",
        who: "Michel de Montaigne",
        work: "Essays",
        year: "1580",
        tags: ["fear", "courage"],
        adapted: false
      },
      {
        id: "q-mt01",
        text: "Travel is fatal to prejudice, bigotry, and narrow-mindedness, and many of our people need it sorely on these accounts.",
        who: "Mark Twain",
        work: "The Innocents Abroad",
        year: "1869",
        tags: ["travel"],
        adapted: false
      },
      {
        id: "q-mt02",
        text: "Courage is resistance to fear, mastery of fear: not absence of fear.",
        who: "Mark Twain",
        work: "Pudd'nhead Wilson",
        year: "1894",
        tags: ["fear", "courage"],
        adapted: true
      },
      {
        id: "q-mt03",
        text: "Truth is the most valuable thing we have. Economize it.",
        who: "Mark Twain",
        work: "Following the Equator",
        year: "1897",
        tags: ["honesty"],
        adapted: false
      },
      {
        id: "q-mt04",
        text: "Be careless in your dress if you must, but keep a tidy soul.",
        who: "Mark Twain",
        work: "Following the Equator",
        year: "1897",
        tags: ["honesty", "discipline"],
        adapted: false
      },
      {
        id: "q-ok01",
        text: "Here with a Loaf of Bread beneath the Bough, a Flask of Wine, a Book of Verse, and Thou beside me singing in the Wilderness, and Wilderness is Paradise enow.",
        who: "Omar Khayyam",
        work: "Rubaiyat of Omar Khayyam",
        year: "1859",
        tags: ["wine", "table", "pleasure"],
        adapted: true
      },
      {
        id: "q-ok02",
        text: "Come, fill the Cup, and in the Fire of Spring the Winter Garment of Repentance fling: the Bird of Time has but a little way to fly, and Lo! the Bird is on the Wing.",
        who: "Omar Khayyam",
        work: "Rubaiyat of Omar Khayyam",
        year: "1859",
        tags: ["wine", "time", "pleasure"],
        adapted: true
      },
      {
        id: "q-ow01",
        text: "I can resist everything except temptation.",
        who: "Oscar Wilde",
        work: "Lady Windermere's Fan",
        year: "1892",
        tags: ["pleasure", "wit"],
        adapted: false
      },
      {
        id: "q-ow02",
        text: "We are all in the gutter, but some of us are looking at the stars.",
        who: "Oscar Wilde",
        work: "Lady Windermere's Fan",
        year: "1892",
        tags: ["pleasure", "hope"],
        adapted: false
      },
      {
        id: "q-ow03",
        text: "The truth is rarely pure and never simple.",
        who: "Oscar Wilde",
        work: "The Importance of Being Earnest",
        year: "1895",
        tags: ["honesty", "wit"],
        adapted: false
      },
      {
        id: "q-pl01",
        text: "It has passed into a proverb that in wine there is truth.",
        who: "Pliny the Elder",
        work: "Natural History",
        year: "c. 77",
        tags: ["wine", "honesty"],
        adapted: false
      },
      {
        id: "q-pl02",
        text: "Fortune favours the bold.",
        who: "Pliny the Elder",
        work: "as reported by Pliny the Younger, Letters",
        year: "79",
        tags: ["courage", "fear"],
        adapted: false
      },
      {
        id: "q-rs01",
        text: "I travel not to go anywhere, but to go. I travel for travel's sake. The great affair is to move.",
        who: "Robert Louis Stevenson",
        work: "Travels with a Donkey in the C\u00e9vennes",
        year: "1879",
        tags: ["travel"],
        adapted: true
      },
      {
        id: "q-rs02",
        text: "The wine is bottled poetry.",
        who: "Robert Louis Stevenson",
        work: "The Silverado Squatters",
        year: "1883",
        tags: ["wine"],
        adapted: false
      },
      {
        id: "q-sj01",
        text: "I look upon it, that he who does not mind his belly will hardly mind anything else.",
        who: "Samuel Johnson",
        work: "as recorded by Boswell, The Life of Samuel Johnson",
        year: "1763",
        tags: ["table", "hunger", "discipline"],
        adapted: false
      },
      {
        id: "q-sj02",
        text: "There is nothing which has yet been contrived by man by which so much happiness is produced as by a good tavern or inn.",
        who: "Samuel Johnson",
        work: "as recorded by Boswell, The Life of Samuel Johnson",
        year: "1776",
        tags: ["hospitality", "bar", "pleasure"],
        adapted: false
      },
      {
        id: "q-sn01",
        text: "It is not the man who has too little, but the man who craves more, that is poor.",
        who: "Seneca",
        work: "Letters to Lucilius",
        year: "c. 64",
        tags: ["discipline", "hunger", "generosity"],
        adapted: false
      },
      {
        id: "q-sn02",
        text: "It is not that we have a short space of time, but that we waste much of it.",
        who: "Seneca",
        work: "On the Shortness of Life",
        year: "c. 49",
        tags: ["discipline", "work", "time"],
        adapted: false
      },
      {
        id: "q-tp01",
        text: "There are two reasons for drinking: one is, when you are thirsty, to cure it; the other, when you are not thirsty, to prevent it.",
        who: "Thomas Love Peacock",
        work: "Melincourt",
        year: "1817",
        tags: ["bar", "pleasure"],
        adapted: false
      },
      {
        id: "q-vt01",
        text: "The best is the enemy of the good.",
        who: "Voltaire",
        work: "Philosophical Dictionary",
        year: "1764",
        tags: ["craft", "discipline"],
        adapted: false
      },
      {
        id: "q-vw01",
        text: "One cannot think well, love well, sleep well, if one has not dined well.",
        who: "Virginia Woolf",
        work: "A Room of One's Own",
        year: "1929",
        tags: ["table", "hunger", "pleasure"],
        adapted: false
      },
      {
        id: "q-vw02",
        text: "The lamp in the spine does not light on beef and prunes.",
        who: "Virginia Woolf",
        work: "A Room of One's Own",
        year: "1929",
        tags: ["table", "hunger"],
        adapted: false
      },
      {
        id: "q-wc01",
        text: "Never give in, never give in, never, never, never, never: in nothing, great or small, large or petty, never give in except to convictions of honour and good sense.",
        who: "Winston Churchill",
        work: "Speech at Harrow School",
        year: "1941",
        tags: ["discipline", "courage"],
        adapted: true
      },
      {
        id: "q-ws01",
        text: "Good company, good wine, good welcome, can make good people.",
        who: "William Shakespeare",
        work: "Henry VIII",
        year: "1613",
        tags: ["hospitality", "wine", "table"],
        adapted: false
      }
    ]
  };
})(typeof window !== 'undefined' ? window : this);
