/* First Light: the year's 366 voices (The Philosophers track)
   Extracted verbatim from first_light_year_4.html.
   Declares globals; loaded by a classic <script> tag. */

const MONTHS=[
 ["January","Beginning Again","The Stoics open the year: every dawn a fresh contract, every day a separate life."],
 ["February","Compassion and Kindness","The shortest month carries the widest circle: Confucius on ren, the Stoics on our common bond, the Tao on yielding strength."],
 ["March","Discipline and Habit","What you repeat, you become. The Confucian examiners and the Stoic trainers take the floor."],
 ["April","Renewal and the Way","The world turns green and the Tao runs through it: soft water, uncarved wood, effortless growth."],
 ["May","Wisdom and Counsel","The philosophers and the proverbs of the nations, short words, long tested, meant to be carried in a pocket."],
 ["June","Truth and Clarity","A month for plain speech: the Stoics on honest judgment, Confucius on the rectification of names, the Tao on words that don't boast."],
 ["July","Courage in Trial","High summer, hard roads. The Stoics and the old proverbs speak: fear examined, obstacles turned."],
 ["August","Impermanence","Everything ripens and everything falls. Marcus and Laozi hold the same lesson: change is nature's delight."],
 ["September","Justice and Service","The harvest asks who will be fed. Confucius, Mencius, and Cicero on what is owed to others."],
 ["October","Stillness and Silence","The year quiets. The Tao's emptiness, the Stoics' inner citadel, and the practice of sitting until the water clears."],
 ["November","Gratitude and Mortality","Count the gifts and number the days: the two disciplines that sharpen one another."],
 ["December","Renewal and Hope","The darkest month keeps the oldest secular promise: the seasons turn, and so can you."]
];

const Q={
1:[
[1,"Begin at once to live, and count each separate day as a separate life.","Seneca, Letters 101.10","Stoic"],
[2,"Waste no more time arguing what a good man should be. Be one.","Marcus Aurelius, Meditations 10.16","Stoic","Staniforth’s 1964 wording. The stray “about” is how the line travels online."],
[3,"First say to yourself what you would be; and then do what you have to do.","Epictetus, Discourses 3.23.1","Stoic"],
[4,"When you arise in the morning, think of what a precious privilege it is to be alive.","Elbert Hubbard, The Fra, 1914","Stoic","Carried under Marcus Aurelius for a century. It is nowhere in the Meditations; the words are Hubbard’s."],
[5,"No man is free who is not master of himself.","Attributed to Epictetus","Stoic","Survives only as Fragment 35, which modern editors class among the doubtful and spurious. For the same thought with a real source, see Discourses 4.1."],
[6,"It is not that we have a short time to live, but that we waste a great deal of it.","Seneca, On the Shortness of Life 1.3","Stoic"],
[7,"Confine yourself to the present.","Marcus Aurelius, Meditations 7.29","Stoic"],
[8,"Man conquers the world by conquering himself.","Attributed to Zeno of Citium","Stoic","Found in no ancient source; it appears online from about 2015. The idea is Plato’s: Laws 626e, that the first and best victory is to conquer oneself."],
[9,"We suffer more often in imagination than in reality.","Seneca, Letters 13.4","Stoic"],
[10,"The impediment to action advances action. What stands in the way becomes the way.","Marcus Aurelius, Meditations 5.20","Stoic","The epigram is Gregory Hays’s 2002 compression; no earlier translation reads anything like it."],
[11,"Make the best use of what is in your power, and take the rest as it happens.","Epictetus, Discourses 1.1.17","Stoic"],
[12,"Luck is what happens when preparation meets opportunity.","Anonymous, in print by 1912","Stoic","Circulates as Seneca and is not his. An American maxim from The Youth’s Companion, retrofitted onto him in the late 1990s."],
[13,"You have power over your mind — not outside events. Realize this, and you will find strength.","Attributed to Marcus Aurelius","Stoic","Not in the Meditations, in any translation, and traceable in print only to 2006. It welds Epictetus’s dichotomy of control to Marcus’s doctrine that distress comes from judgement, which is why it passes. For the real thing see Meditations 12.22."],
[14,"Wealth consists not in having great possessions, but in having few wants.","Attributed to Epictetus","Stoic","Absent from the whole surviving corpus. The wording is Joseph Brotherton’s, in the Commons in 1842, itself reported as an echo of Epicurus. The thought is Epictetan; the words are not."],
[15,"While we wait for life, life passes.","After Seneca, Letters 1.2","Stoic","Gummere has “While we are postponing, life speeds by”: dum differtur vita transcurrit. Life rushes past while things are deferred, which is not quite the same as waiting for it."],
[16,"The best revenge is to be unlike him who performed the injury.","After Marcus Aurelius, Meditations 6.6","Stoic","The passage is genuine and one sentence long in the Greek, but this English is no published translator’s. Long: “the best way of avenging thyself is not to become like the wrong-doer.”"],
[17,"It is difficulties that show what men are.","Epictetus, Discourses 1.24.1","Stoic"],
[18,"Hang on to your youthful enthusiasms — you will be able to use them better when you are older.","Attributed to Seneca","Stoic","No Latin original is known, and it appears in none of the 124 letters. Its origin has not been traced."],
[19,"Very little is needed to make a happy life.","After Marcus Aurelius, Meditations 7.67","Stoic","The first clause is Marcus. The rest (“it is all within yourself, in your way of thinking”) is a modern gloss, absent from the Greek and from every standard translation."],
[20,"Only the educated are free.","Epictetus, Discourses 2.1.22","Stoic","An elided variant rather than a translator’s sentence; Long has “the educated only are free.”"],
[21,"As long as you live, keep learning how to live.","Seneca, Letters 76.3","Stoic"],
[22,"Do every act of your life as though it were the very last act of your life.","Marcus Aurelius, Meditations 2.5","Stoic"],
[23,"Circumstances do not make the man; they only reveal him to himself.","James Allen, As a Man Thinketh, 1903","Stoic","Not Epictetus. Compare Discourses 1.24.1: difficulties show what men are to others; the turn inward is Allen’s."],
[24,"He who is brave is free.","After Seneca, Letters 85.24","Stoic","Seneca’s brave man is free from fear, not free as such. The short form gains a meaning the Latin does not carry."],
[25,"The soul becomes dyed with the color of its thoughts.","Marcus Aurelius, Meditations 5.16","Stoic"],
[26,"No great thing is created suddenly, any more than a bunch of grapes or a fig.","Epictetus, Discourses 1.15.7","Stoic"],
[27,"Every night before going to sleep, we must ask ourselves: what weakness did I overcome today?","After Seneca, On Anger 3.36","Stoic","Seneca reports this as the nightly practice of his teacher Sextius. The wording is a modern compression, not a translation."],
[28,"If it is not right, do not do it; if it is not true, do not say it.","Marcus Aurelius, Meditations 12.17","Stoic"],
[29,"Know, first, who you are, and then adorn yourself accordingly.","Epictetus, Discourses 3.1.25","Stoic"],
[30,"Well-being is attained little by little, and nevertheless is no little thing itself.","Zeno of Citium, in Diogenes Laertius 7.26","Stoic","Diogenes adds that others ascribe the saying to Socrates."],
[31,"Look back over the past, with its changing empires that rose and fell, and you can foresee the future too.","Marcus Aurelius, Meditations 7.49, freely rendered","Stoic","“Empires that rose and fell” is a translator’s flourish; Marcus wrote of changes of dominion."],
],
2:[
[1,"To love all men — this is humanity.","Confucius, Analects 12.22","Confucian"],
[2,"As you are a part of a social system, let every act of yours be of benefit to the whole.","After Marcus Aurelius, Meditations 9.23","Stoic","The passage is at 9.23, not 7.13. Long has “let every act of thine be a component part of social life”, a claim about membership, where “be of benefit to the whole” makes it one about usefulness."],
[3,"Wherever there is a human being, there is an opportunity for kindness.","Seneca, De Vita Beata 24.3","Stoic"],
[4,"I have three treasures which I hold and keep: mercy, frugality, and humility.","Laozi, Tao Te Ching 67","Taoist","The third treasure is 不敢為天下先, not daring to be first in the world. “Humility” compresses a refusal into a virtue, and the chapter’s argument runs on the refusal."],
[5,"The feeling of compassion is the beginning of humanity.","Mencius 2A6","Confucian"],
[6,"He who loves others is constantly loved by them.","Mencius 4B28","Confucian"],
[7,"A kind word warms three winters.","Chinese proverb, from the Zengguang Xianwen","Chinese","A Ming-dynasty primer, not a floating saying. 三冬 is the three months of one winter rather than three winters; the English is the standard rendering, but it counts wrong."],
[8,"A single kind act, like a stone in water, sends ripples beyond sight.","Source unknown","Wisdom","Calling this a proverb claims a traditional pedigree it does not have. No source of any age has been found for it."],
[9,"Do not do to others what you would not want done to yourself.","Confucius, Analects 15.24","Confucian","Legge numbers this passage 15.23; 15.24 is the modern scheme used by Lau, Slingerland and the Chinese Text Project."],
[10,"The superior man seeks harmony, not sameness.","Confucius, Analects 13.23","Confucian"],
[11,"He who is kind to others is at peace with himself.","Source unknown","Wisdom","Not found in the Sententiae. Syrus does have a maxim close to it (semper beatam se putat benignitas, “kindness always thinks itself happy”) but it is not this sentence."],
[12,"No act of kindness, no matter how small, is ever wasted.","Aesop, The Lion and the Mouse","Greek","The fable is real and identifiable, but this wording comes from The Aesop for Children, 1919, whose moral runs “A kindness is never wasted.”"],
[13,"Give, and it enriches you more than it costs the giver.","Attributed to Publilius Syrus","Roman","The line is internally incoherent: it enriches “you” more than it costs “the giver”, making one person both parties, which is the fingerprint of a corrupted quotation. Syrus wrote: beneficium dando accepit, qui digno dedit: he who gave to a worthy man received by the giving."],
[14,"The best men are like water, which benefits all things and does not compete with them.","Laozi, Tao Te Ching 8","Taoist"],
[15,"Anyone can become angry — that is easy. But to be angry with the right person, to the right degree, at the right time, for the right purpose — that is not easy.","After Aristotle, Nicomachean Ethics 1109a26","Greek","The passage is Aristotle’s, but the circulating English has been edited twice over and matches no published translation. Ross also has him listing giving and spending money alongside anger."],
[16,"A youth, when at home, should be filial; abroad, respectful to elders.","Confucius, Analects 1.6","Confucian"],
[17,"Cherish some man of high character, and keep him ever before your eyes, living as if he were watching you.","Seneca, Letters 11.8","Stoic"],
[18,"The perfect man has no self; the spiritual man has no achievement; the sage has no name.","Zhuangzi, Inner Chapters 1","Taoist"],
[19,"Kindness in words creates confidence. Kindness in thinking creates profoundness. Kindness in giving creates love.","Author unknown","Wisdom","Not from the Tao Te Ching and not Laozi’s. “Attributed to” was too generous: the attribution is not contested but false, traceable to a twentieth-century anthology. The Taoist tag went with the name."],
[20,"When you have done a good act and another has received it, why do you look besides for a third thing — praise for having done good, or a return?","Marcus Aurelius, Meditations 7.73","Stoic"],
[21,"Fine words and an insinuating appearance are seldom associated with true virtue.","Confucius, Analects 1.3","Confucian"],
[22,"He who requites injury with kindness is a man of excellent virtue.","After Laozi, Tao Te Ching 63","Taoist","Legge’s clause is simply “recompense injury with kindness”. The added praise for excellent virtue is not in the chapter, and it happens to endorse the exact position Confucius rejects at Analects 14.34."],
[23,"It is the act of an ill-instructed man to blame others for his own bad condition; it is the act of one who has begun to be instructed, to lay the blame on himself; and of one whose instruction is completed, neither to blame another, nor himself.","Epictetus, Enchiridion 5","Stoic","The middle stage was missing. Epictetus describes a progression (blame others, then blame yourself, then blame no one) and cutting the second step turns a course of training into a contrast between the ignorant and the wise."],
[24,"A man of humanity, wishing to be established himself, seeks to establish others.","Confucius, Analects 6.30","Confucian","Legge numbers this 6.28; 6.30 is the modern scheme."],
[25,"The sage does not accumulate for himself. The more he does for others, the more he has.","Laozi, Tao Te Ching 81","Taoist"],
[26,"Virtue is not left to stand alone. He who practices it will have neighbors.","Confucius, Analects 4.25","Confucian"],
[27,"How much more grievous are the consequences of anger than the causes of it.","After Marcus Aurelius, Meditations 11.18","Stoic","The eighth of the ten thoughts Marcus sets down against anger. The wording is a compression rather than any translator’s sentence."],
[28,"The soft overcomes the hard; the weak overcomes the strong.","Laozi, Tao Te Ching 36","Taoist"],
[29,"To subdue oneself and return to propriety is perfect virtue.","Confucius, Analects 12.1","Confucian"],
],
3:[
[1,"Each day I examine myself on three counts: faithfulness, sincerity, practice.","After Zengzi, Analects 1.4","Confucian","Zengzi asks these as questions about failure rather than naming three virtues, and no translator writes this sentence. The third divides them: Legge and Waley read it as what his teacher handed down, Lau and Slingerland as what he has taught without practising."],
[2,"It does not matter how slowly you go as long as you do not stop.","Author unknown","Wisdom","Not in the Analects, and no Chinese text of any age has been produced for it. Where the English came from has not been traced. The thought is real enough: Analects 9.19, the mound abandoned one basketful short."],
[3,"Every habit and faculty is maintained and increased by the corresponding actions.","Epictetus, Discourses 2.18.1","Stoic"],
[4,"The man who moves a mountain begins by carrying away small stones.","Author unknown","Wisdom","Not in the Analects, and absent from both standard Victorian collections of Chinese proverbs, Davis 1836 and Scarborough 1875. It circulates as often as a Chinese proverb as under Confucius. The image recalls the Foolish Old Man of the Liezi, who carried the mountain away in baskets."],
[5,"When you know a thing, hold that you know it; when you do not, allow that you do not — this is knowledge.","Confucius, Analects 2.17","Confucian","Legge’s wording, lightly compressed. He keeps the Master’s opening address: “Yu, shall I teach you what knowledge is?”, Yu being the disciple Zilu, who is being corrected to his face."],
[6,"Discipline is the refining fire by which talent becomes ability.","Roy L. Smith, Splinters, 1929","Wisdom","Not a proverb. It stands on page 53 of Splinters, Roy L. Smith’s 1929 collection of sentence sermons, under the heading “Discipline”. Contemporary notices call the book assembled as well as written, so his authorship of this line is likely rather than certain."],
[7,"The superior man is modest in his speech but exceeds in his actions.","Confucius, Analects 14.27","Confucian","Legge numbers this passage 14.29, and this English is his; 14.27 is the modern scheme used by Lau, Slingerland and the Chinese Text Project."],
[8,"Though a piece of wood is as straight as a plumb line, if it is bent with force it can be made into a wheel.","After Xunzi 1, Encouraging Learning","Confucian","Xunzi’s 輮 is the craftsman’s steam-bending rather than force, and his point is that the curve is permanent: Watson has “even after the wood has dried, it will not straighten out again.” The English here is no translator’s."],
[9,"He who learns but does not think is lost. He who thinks but does not learn is in great danger.","Confucius, Analects 2.15","Confucian","The English is Arthur Waley’s, 1938. Legge’s 2.15 reads quite differently: “Learning without thought is labour lost; thought without learning is perilous.”"],
[10,"First, do nothing inconsiderately, nor without a purpose.","Marcus Aurelius, Meditations 12.20","Stoic","The passage is at 12.20, not 4.2; Long’s 4.2 is a different maxim that also turns on purpose, which is likely how the slip happened. Marcus gives a second rule with it: “make thy acts refer to nothing else than to a social end.”"],
[11,"The gem cannot be polished without friction, nor man perfected without trials.","Chinese proverb","Chinese","In English as a Chinese proverb since at least 1836, when John Francis Davis printed it among his aphorisms: “nor man perfected without adversity”. The Chinese shape is 玉不琢不成器，人不磨不成道: jade uncut forms no vessel, a man unground attains no way."],
[12,"I hear and I forget. I see and I remember. I do and I understand.","Attributed to Xunzi","Confucian","A twentieth-century classroom maxim, not a translation of anything. The nearest real text is Xunzi 8, 儒效: not hearing is not as good as hearing, hearing as seeing, seeing as knowing, knowing as doing: five rungs, and no forgetting in any of them."],
[13,"Those who know do not speak; those who speak do not know.","Laozi, Tao Te Ching 56","Taoist","Arthur Waley’s 1934 wording, exactly. Legge glosses more heavily, “He who knows (the Tao) does not (care to) speak (about it)”, but the Chinese, 知者不言，言者不知, is as bare as Waley makes it."],
[14,"Real knowledge is to know the extent of one's ignorance.","Attributed to Confucius","Confucian","Not in the Analects: five complete translations contain neither this sentence nor the phrase “real knowledge”. The thought it answers to is 2.17, knowing what you know and admitting what you do not; measuring the extent of one’s ignorance is a Socratic turn Confucius never takes."],
[15,"Men’s natures are alike; it is their habits that carry them far apart.","Confucius, Analects 17.2","Confucian","The reference is right; the English had drifted. Lionel Giles (1907) wrote it this way. 性相近 is near to one another, not the same: Confucius stops short of identical natures, and that gap is exactly what Mencius and Xunzi went on to argue about."],
[16,"By perseverance the snail reached the ark.","Proverb, from Spurgeon’s The Salt-Cellars, 1889","Wisdom","Gathered by C. H. Spurgeon in The Salt-Cellars, 1889, page 89, with his own gloss: “the snails started early, and by keeping on they entered the ark.” The image is older than the proverb: a Methodist blacksmith’s consolation, in print by 1832."],
[17,"Just as in building a mound, if I stop before the last basketful of earth is placed, I stop of my own accord.","Confucius, Analects 9.19","Confucian","Legge numbers this 9.18: from Book IX chapter VII he runs one behind the modern scheme the almanac follows. The English is no published translation; Lau is nearest: “if, before the very last basketful, I stop, then I shall have stopped.”"],
[18,"No man was ever wise by chance.","Seneca, Letters 76.6","Stoic","Seneca’s Latin at 76.6 is nulli sapere casu obtigit. The English is an epigram in circulation rather than any published translation; Gummere’s Loeb renders it “Wisdom comes haphazard to no man”."],
[19,"Learning should never cease.","Xunzi 1, Encouraging Learning","Confucian","The opening line of the Xunzi’s first chapter, where the text puts it in the mouth of “the gentleman” rather than stating it in Xunzi’s own voice. The wording is Burton Watson’s; Hutton has “Learning must never stop”."],
[20,"Practice yourself, for heaven's sake, in little things, and thence proceed to greater.","Epictetus, Discourses 1.18.18","Stoic","Higginson’s wording, revising Elizabeth Carter’s 1758 “Exercise yourself, for Heaven’s sake, in little things”; the Greek really does swear by the gods. The little things Epictetus has in view are a headache and an earache."],
[21,"Hold faithfulness and sincerity as first principles.","Confucius, Analects 1.8","Confucian","One of the four counsels of Analects 1.8; day 31 carries another. All three recur verbatim later in the book, at 9.25, which is 9.24 in Legge."],
[22,"Nothing in the world is impossible for the one whose heart is set upon it.","Chinese proverb, in Journey to the West, chapter 2","Chinese","The Chinese is 世上無難事，只怕有心人, the Patriarch’s answer when Wukong protests that cloud-soaring is beyond him. Older forms survive: the Shilin Guangji has 人心自不堅, it is the heart that is not firm. 難事 is a hard thing rather than an impossible one."],
[23,"The superior man thinks of virtue; the small man thinks of comfort.","Confucius, Analects 4.11","Confucian","Verbatim Legge, and 4.11 in his numbering and the modern one alike. 懷土 is where translators part company: Legge’s “comfort” glosses a word meaning earth or land, which Muller renders “material things” and Lau “his native land”."],
[24,"If you work at that which is before you, following right reason seriously and vigorously, you will live happily.","After Marcus Aurelius, Meditations 3.12","Stoic","Long’s sentence, abridged. He gives three adverbs, “seriously, vigorously, calmly”, and the third, εὐμενῶς, is the one translators dispute: Farquharson has “with kindness”. Marcus also makes the happy life conditional on expecting nothing and fearing nothing."],
[25,"Study the past if you would divine the future.","Anonymous, in print by 1872","Confucian","Not in the Analects, and no Chinese original has ever been produced. The earliest print appearance found is Ballou’s Treasury of Thought, 1872, which sets it under PAST with nothing but the name attached. “Divine” is the nineteenth-century form; “define” is a later drift that turns foreseeing into shaping."],
[26,"Practice is the hardest part of learning, and training is the essence of transformation.","Ann Voskamp, One Thousand Gifts, 2010","Wisdom","Not a proverb, and not old. It is Ann Voskamp’s own sentence, from One Thousand Gifts, 2010, a modern devotional book. It appears nowhere in print before it, and no tradition has ever claimed it."],
[27,"Men are disturbed not by the things which happen, but by their opinions about the things.","Epictetus, Enchiridion 5","Stoic","Long’s wording with one word added; he has “the opinions about the things”. The possessive belongs to Oldfather’s line, “their judgements”. Epictetus makes it personal himself a few lines on: “that is, our opinions”."],
[28,"The cautious seldom err.","Confucius, Analects 4.23","Confucian","Legge’s phrasing. 約 is self-restraint, or holding to essentials, rather than caution about risk; Waley has “Those who err on the side of strictness are few indeed”."],
[29,"To see what is right and not to do it is want of courage.","Confucius, Analects 2.24","Confucian"],
[30,"Is it not pleasant to learn with a constant perseverance and application?","Confucius, Analects 1.1","Confucian","Legge’s phrasing, and the first of the three questions that open the Analects. 時習 is practice at due times rather than perseverance as such; Waley has “to learn and at due times to repeat what one has learnt”."],
[31,"When you have faults, do not fear to abandon them.","Confucius, Analects 1.8","Confucian","The last of the four counsels in Analects 1.8. The same three counsels recur verbatim later in the book, at 9.25, which is 9.24 in Legge."],
],
4:[
[1,"Nature does not hurry, yet everything is accomplished.","Attributed to Laozi","Taoist","Not found in the Tao Te Ching. The line is a modern gloss on chapter 37, where the Tao does nothing and yet leaves nothing undone; Legge’s text is in the Library."],
[2,"A journey of a thousand miles begins with a single step.","Laozi, Tao Te Ching 64","Taoist"],
[3,"Nothing in the world is as soft and yielding as water, yet for dissolving the hard and inflexible, nothing surpasses it.","Laozi, Tao Te Ching 78","Taoist"],
[4,"Knowing others is intelligence; knowing yourself is true wisdom.","Laozi, Tao Te Ching 33","Taoist"],
[5,"When I let go of what I am, I become what I might be.","Attributed to Laozi","Taoist"],
[6,"The sage does not attempt anything very big, and thus achieves greatness.","Laozi, Tao Te Ching 63","Taoist"],
[7,"To the mind that is still, the whole universe surrenders.","Attributed to Zhuangzi","Taoist"],
[8,"He who knows that enough is enough will always have enough.","Laozi, Tao Te Ching 46","Taoist"],
[9,"Flow with whatever may happen, and let your mind be free.","Zhuangzi, Inner Chapters","Taoist"],
[10,"The ancient masters were profound and subtle; their wisdom was unfathomable.","Laozi, Tao Te Ching 15","Taoist"],
[11,"He who stands on tiptoe is not steady. He who strides cannot maintain the pace.","Laozi, Tao Te Ching 24","Taoist"],
[12,"Great understanding is broad and unhurried; little understanding is cramped and busy.","Zhuangzi, Inner Chapters","Taoist"],
[13,"Better to stop short than fill to the brim.","Laozi, Tao Te Ching 9","Taoist"],
[14,"In pursuit of knowledge, every day something is added. In practice of the Tao, every day something is dropped.","Laozi, Tao Te Ching 48","Taoist"],
[15,"The journey of the Tao is a return.","Laozi, Tao Te Ching 40","Taoist"],
[16,"Do the difficult things while they are easy, and the great things while they are small.","Laozi, Tao Te Ching 63","Taoist"],
[17,"Muddy water, let stand, becomes clear.","Attributed to Laozi","Taoist"],
[18,"The superior man blames himself; the small man blames others.","Confucius, Analects 15.20","Confucian"],
[19,"Life is the companion of death, death is the beginning of life. Who understands their working?","Zhuangzi, Zhi Bei You","Taoist"],
[20,"The living are soft and yielding; the dead are hard and stiff. The soft and supple will prevail.","Laozi, Tao Te Ching 76","Taoist"],
[21,"The bamboo that bends is stronger than the oak that resists.","Japanese proverb","Japanese"],
[22,"Where can I find a man who has forgotten words, so that I can have a word with him?","Zhuangzi, Waiwu","Taoist"],
[23,"He who by reanimating the old can gain knowledge of the new is fit to be a teacher.","Confucius, Analects 2.11","Confucian"],
[24,"The Tao that can be told is not the eternal Tao.","Laozi, Tao Te Ching 1","Taoist"],
[25,"Fall down seven times, stand up eight.","Japanese proverb","Japanese"],
[26,"Yield and overcome; bend and be straight; empty and be full.","Laozi, Tao Te Ching 22","Taoist"],
[27,"Renew yourself completely each day; do it again, and again, and forever again.","Inscription of King Tang, cited in the Great Learning","Confucian"],
[28,"The softest thing in the universe overcomes the hardest thing in the universe.","Laozi, Tao Te Ching 43","Taoist"],
[29,"The fish trap exists because of the fish; once you've gotten the fish, you can forget the trap.","Zhuangzi, Waiwu","Taoist"],
[30,"A tree that fills a man's embrace grows from a tiny sprout.","Laozi, Tao Te Ching 64","Taoist"],
],
5:[
[1,"To know yet to think that one does not know is best; not to know yet to think that one knows is a disease.","Laozi, Tao Te Ching 71","Taoist"],
[2,"A rolling stone gathers no moss.","Publilius Syrus, Sentences","Roman"],
[3,"Character is destiny.","Heraclitus, Fragment 119","Greek"],
[4,"Many much-learned men have no understanding.","Democritus, Fragment","Greek"],
[5,"A book holds a house of gold.","Chinese proverb","Chinese"],
[6,"When you see a man of worth, think of how you may equal him. When you see one who is unworthy, examine yourself.","Confucius, Analects 4.17","Confucian"],
[7,"A scholar whose mind is set on truth, and who is ashamed of bad clothes and bad food, is not fit to be discoursed with.","Confucius, Analects 4.9","Confucian"],
[8,"It is a bad plan that admits of no modification.","Publilius Syrus, Sentences","Roman"],
[9,"Not to know is bad. Not to want to know is worse.","Xunzi","Confucian"],
[10,"The pursuit, even of the best things, ought to be calm and tranquil.","Cicero, De Officiis","Roman"],
[11,"True words are not beautiful; beautiful words are not true. Good men do not argue; those who argue are not good.","Laozi, Tao Te Ching 81","Taoist"],
[12,"Not what we have but what we enjoy constitutes our abundance.","Epicurus","Greek"],
[13,"I do not enlighten those who are not eager to learn.","Confucius, Analects 7.8","Confucian"],
[14,"Silence is better than unmeaning words.","Attributed to Pythagoras","Greek"],
[15,"A wise man adapts himself to circumstances, as water shapes itself to the vessel that contains it.","Chinese proverb","Chinese"],
[16,"A room without books is like a body without a soul.","Cicero","Roman"],
[17,"The gentleman devotes his mind to the accumulation of good.","Xunzi","Confucian"],
[18,"Never find fault with the absent.","Publilius Syrus, Sentences","Roman"],
[19,"The object of the superior man is truth; food is not his object.","Confucius, Analects 15.31","Confucian"],
[20,"It is greed to do all the talking and not want to listen at all.","Democritus, Fragment","Greek"],
[21,"You must linger among a limited number of master-thinkers, and digest their works, if you would derive ideas which win firm hold in your mind.","Seneca, Letters 2","Stoic"],
[22,"Teachers open the door. You enter by yourself.","Chinese proverb","Chinese"],
[23,"The life of the dead is placed in the memory of the living.","Cicero, Philippicae","Roman"],
[24,"There were four things the Master wholly cut off: opinionatedness, dogmatism, obstinacy, egoism.","Confucius, Analects 9.4","Confucian"],
[25,"Much learning does not teach understanding.","Heraclitus, Fragment 40","Greek"],
[26,"Practice is the best of all instructors.","Publilius Syrus, Sentences","Roman"],
[27,"My words are very easy to know, and very easy to practice; but there is no one in the world able to know and able to practice them.","Laozi, Tao Te Ching 70","Taoist"],
[28,"Without trust, we cannot stand.","Confucius, Analects 12.7","Confucian"],
[29,"Never call yourself a philosopher, nor talk a great deal among the unlearned about theorems, but act conformably to them.","Epictetus, Enchiridion 46","Stoic"],
[30,"Give a man a fish and you feed him for a day; teach a man to fish and you feed him for a lifetime.","Chinese proverb","Chinese","Its origin is unattested. The earliest printing found is in English, in Anne Isabella Thackeray Ritchie’s novel Mrs. Dymond (1885), and no Chinese source has been located."],
[31,"The function of wisdom is to discriminate between good and evil.","Cicero, De Officiis","Roman"],
],
6:[
[1,"First learn the meaning of what you say, and then speak.","Epictetus, Discourses 2.17","Stoic"],
[2,"I do not know how a man without truthfulness is to get on.","Confucius, Analects 2.22","Confucian"],
[3,"If any man can convince me and show me that I do not think or act right, I will gladly change.","Marcus Aurelius, Meditations 6.21","Stoic"],
[4,"Great perfection seems imperfect, yet it does not decay.","Laozi, Tao Te Ching 45","Taoist"],
[5,"Believe not each accusing tongue.","Publilius Syrus, Sentences","Roman"],
[6,"A gentleman's words are precise; a petty man's words are elaborate.","Xunzi","Confucian"],
[7,"Nothing is so incredible that oratory cannot make it acceptable — which is why plain truth needs no ornament.","Cicero, De Oratore","Roman"],
[8,"The sun is new each day.","Heraclitus, Fragment 6","Greek"],
[9,"Of things, some are in our power, and others are not.","Epictetus, Enchiridion 1","Stoic"],
[10,"The superior man wishes to be slow in his words and earnest in his conduct.","Confucius, Analects 4.24","Confucian"],
[11,"Let it be your earnest and constant care to perform whatever you are about with true and unfeigned gravity.","Marcus Aurelius, Meditations 8.5","Stoic"],
[12,"He who does not boast is acknowledged; he who does not brag will endure.","Laozi, Tao Te Ching 22","Taoist"],
[13,"Great truths do not take hold of the hearts of the masses.","Zhuangzi","Taoist"],
[14,"We know nothing in reality, for truth lies in an abyss.","Democritus, Fragment 117","Greek"],
[15,"Hearing one point, to know ten others.","Confucius, Analects 5.9","Confucian"],
[16,"The judge is condemned when the criminal is acquitted.","Publilius Syrus, Sentences","Roman"],
[17,"The foundation of justice is good faith.","Cicero, De Officiis","Roman"],
[18,"If language is not correct, then what is said is not what is meant.","Confucius, Analects 13.3","Confucian"],
[19,"The Tao that is bright seems dim.","Laozi, Tao Te Ching 41","Taoist"],
[20,"Speech is not merely the blowing of breath. It is intended to say something.","Zhuangzi, Discussion on Making All Things Equal","Taoist"],
[21,"How much trouble he avoids who does not look to see what his neighbor says or does.","Marcus Aurelius, Meditations 4.18","Stoic"],
[22,"The palest ink is better than the best memory.","Chinese proverb","Chinese"],
[23,"Fine words confound virtue.","Confucius, Analects 15.27","Confucian"],
[24,"Eyes are more accurate witnesses than ears.","Heraclitus, Fragment 101a","Greek"],
[25,"Remember that you are an actor in a play; your business is to act well the part that is given to you.","Epictetus, Enchiridion 17","Stoic"],
[26,"True words seem paradoxical.","Laozi, Tao Te Ching 78","Taoist"],
[27,"It is not every question that deserves an answer.","Publilius Syrus, Sentences","Roman"],
[28,"The relation between superiors and inferiors is like that between the wind and the grass; the grass must bend when the wind blows.","Confucius, Analects 12.19","Confucian"],
[29,"The universe is change; life is opinion.","Marcus Aurelius, Meditations 4.3","Stoic"],
[30,"The wise man looks into space and does not regard the small as too little, nor the great as too much.","Zhuangzi, Autumn Floods","Taoist"],
],
7:[
[1,"At dawn, when you have trouble getting out of bed, tell yourself: I have to go to work — as a human being.","Marcus Aurelius, Meditations 5.1","Stoic"],
[2,"A brave man overcomes not only his enemies but his own fears.","Cicero, tradition","Roman"],
[3,"He who has great trials to bear finds in them the trial of himself.","Seneca, De Providentia","Stoic"],
[4,"Danger breeds best on too much confidence.","Publilius Syrus, Sentences","Roman"],
[5,"Fire is the test of gold; adversity, of strong men.","Seneca, De Providentia","Stoic"],
[6,"Disease attacks the body, but pain, if we cannot conquer it, we can at least disdain.","Seneca, Letters 78","Stoic"],
[7,"It is in your power to think no evil, and even if someone tries to make you feel injured, resist the impression.","Marcus Aurelius, Meditations 11.18","Stoic"],
[8,"A smooth sea never made a skilled sailor.","Proverb","Wisdom"],
[9,"Wipe out imagination; check desire; extinguish appetite.","Marcus Aurelius, Meditations 9.7","Stoic"],
[10,"The bravest sight in the world is to see a great man struggling against adversity.","Seneca","Stoic"],
[11,"No man is more unhappy than he who never faces adversity; he is not permitted to prove himself.","Seneca, De Providentia 4","Stoic"],
[12,"Be like the rock that the waves keep crashing over. It stands unmoved and the raging of the sea falls still around it.","Marcus Aurelius, Meditations 4.49","Stoic"],
[13,"Difficulties strengthen the mind, as labor does the body.","Seneca","Stoic"],
[14,"Sometimes even to live is an act of courage.","Seneca, Letters 78","Stoic"],
[15,"He suffers more than necessary, who suffers before it is necessary.","Seneca, Letters 13","Stoic"],
[16,"Do not be ashamed of needing help. You have a duty to fulfill like a soldier on the wall of battle.","Marcus Aurelius, Meditations 7.7","Stoic"],
[17,"Fortune favors the bold.","Terence, Phormio","Roman"],
[18,"On the occasion of every accident that befalls you, remember to turn to yourself and inquire what power you have for turning it to use.","Epictetus, Enchiridion 10","Stoic"],
[19,"Do not seek to have events happen as you wish, but wish them to happen as they do happen, and you will go on well.","Epictetus, Enchiridion 8","Stoic"],
[20,"Victory belongs to the one who is full of faith.","Publilius Syrus, tradition","Roman"],
[21,"I judge you unfortunate because you have never lived through misfortune.","Seneca, De Providentia 3","Stoic"],
[22,"Where a man can live, there he can also live well.","Marcus Aurelius, Meditations 7.64","Stoic"],
[23,"Necessity gives the law, without itself obeying one.","Publilius Syrus, Sentences","Roman"],
[24,"When you are going to work on some project, remind yourself of what sort of project it is, so that you are not overwhelmed.","Epictetus, Enchiridion 34","Stoic"],
[25,"When the shoe fits, the foot is forgotten.","Zhuangzi, The Turning of Heaven","Taoist"],
[26,"Say to yourself in the morning: I shall meet those who are meddling, ungrateful, arrogant. This has happened to them through their ignorance.","Marcus Aurelius, Meditations 2.1","Stoic"],
[27,"If you are pained by any external thing, it is not this thing that disturbs you, but your own judgment about it — and it is in your power to wipe out this judgment now.","Marcus Aurelius, Meditations 8.47","Stoic"],
[28,"The obstacle in the path becomes the path.","Marcus Aurelius, tradition","Stoic"],
[29,"True happiness is to enjoy the present, without anxious dependence upon the future.","Seneca, Letters 15","Stoic"],
[30,"Endurance is one of the most difficult disciplines, but it is to the one who endures that the final victory comes.","Proverb","Wisdom"],
[31,"Have patience. All things are difficult before they become easy.","Saadi, Gulistan","Persian"],
],
8:[
[1,"All existing things soon change; they will either be reduced to vapor, or be dispersed.","Marcus Aurelius, Meditations 4.35","Stoic"],
[2,"You could leave life right now. Let that determine what you do and say and think.","Marcus Aurelius, Meditations 2.11","Stoic"],
[3,"Life and death are one thread, the same line viewed from different sides.","Zhuangzi","Taoist"],
[4,"This too shall pass.","Persian adage","Persian"],
[5,"He who has learned to die has unlearned slavery; he is above all power, or at least beyond it.","Seneca, Letters 26","Stoic"],
[6,"Do not act as if you had ten thousand years to throw away. Death stands at your elbow.","Marcus Aurelius, Meditations 4.17","Stoic"],
[7,"Time is a river of passing events, and strong is its current.","Marcus Aurelius, Meditations 4.43","Stoic"],
[8,"That which shrinks must first expand. That which fails must first be strong.","Laozi, Tao Te Ching 36","Taoist"],
[9,"Though you were to live three thousand years, know that no man loses any other life than that which he lives, nor lives any other than that which he loses.","Marcus Aurelius, Meditations 2.14","Stoic"],
[10,"The perfect man employs his mind as a mirror; it grasps nothing, refuses nothing, receives but does not keep.","Zhuangzi, Fit for Emperors and Kings","Taoist"],
[11,"Being and non-being produce each other.","Laozi, Tao Te Ching 2","Taoist"],
[12,"Cattle die, kindred die, every man is mortal; but the good name never dies of one who has done well.","Hávamál","Norse"],
[13,"The time of a man's life is a point; his existence a flowing wave; his sense a dim rushlight.","Marcus Aurelius, Meditations 6.36","Stoic"],
[14,"Reversal is the movement of the Tao.","Laozi, Tao Te Ching 40","Taoist"],
[15,"The universe gave me my form, my life, my old age, my death — and it is fitting.","Zhuangzi, The Great Teacher","Taoist"],
[16,"In a little while you will have forgotten the world, and in a little while the world will have forgotten you.","Marcus Aurelius, Meditations 5.33","Stoic"],
[17,"Life is a series of natural and spontaneous changes. Do not resist them; that only creates sorrow.","Attributed to Laozi","Taoist"],
[18,"All conditioned things are subject to decay. Strive on with diligence.","Proverb, ancient wisdom tradition","Wisdom","The Buddha’s reported last words, Mahāparinibbāna Sutta. Kept for what it says; the tradition itself lives in the Library."],
[19,"The nature of the universe changes the things which are, and makes new things of the like form.","Marcus Aurelius, Meditations 9.28","Stoic"],
[20,"It is not possible to step twice into the same river.","Heraclitus, Fragment 91","Greek"],
[21,"Loss is nothing else but change, and change is Nature's delight.","Marcus Aurelius, Meditations 4.51","Stoic"],
[22,"There is a time for being ahead, a time for being behind.","Laozi, Tao Te Ching 29","Taoist"],
[23,"No one has ever been the same person leaving as they were entering.","Seneca, Letters 4","Stoic"],
[24,"The tree that is unbending is easily broken.","Chinese proverb","Chinese"],
[25,"Some things are hurrying into existence, others out of it.","Marcus Aurelius, Meditations 6.15","Stoic"],
[26,"No one knows what the morrow will bring.","Publilius Syrus, Sentences","Roman"],
[27,"A whirlwind does not last a whole morning; a rainstorm does not last a whole day.","Laozi, Tao Te Ching 23","Taoist"],
[28,"It is not death that a man should fear; he should fear never beginning to live.","Marcus Aurelius, tradition","Stoic"],
[29,"To regard the end as the beginning — this is the reason of Heaven.","Zhuangzi, The Great Teacher","Taoist"],
[30,"You will soon be dead, and yet you are not yet simple, nor tranquil.","Marcus Aurelius, Meditations 4.37","Stoic"],
[31,"The best time to plant a tree was twenty years ago. The second best time is now.","Chinese proverb","Chinese"],
],
9:[
[1,"Life is what I want, and righteousness is what I want. If I cannot keep both, I will let life go and choose righteousness.","Mencius 6A10","Confucian"],
[2,"Justice is the source from which all other virtues arise.","Marcus Aurelius, tradition","Stoic"],
[3,"Justice is the crowning glory of the virtues.","Cicero, De Officiis","Roman"],
[4,"When a prince's personal conduct is correct, his government is effective without the issuing of orders.","Confucius, Analects 13.6","Confucian"],
[5,"Let a fair trial be accorded even to the guilty.","Publilius Syrus, Sentences","Roman"],
[6,"The ruler is the boat; the people are the water. The water can support the boat, or the water can capsize it.","Xunzi","Confucian"],
[7,"Whatever is beneficial to the whole swarm is beneficial to the bee.","Marcus Aurelius, Meditations 6.54","Stoic"],
[8,"He who receives a benefit with gratitude repays the first installment of it.","Seneca, De Beneficiis","Stoic"],
[9,"Recompense injury with justice, and recompense kindness with kindness.","Confucius, Analects 14.34","Confucian"],
[10,"When the rich wage war, it is the poor who die.","Proverb","Wisdom"],
[11,"The safety of the people shall be the highest law.","Cicero, De Legibus","Roman"],
[12,"To rule a country of a thousand chariots, there must be reverent attention to business, sincerity, economy, and love for the people.","Confucius, Analects 1.5","Confucian"],
[13,"It is designed by nature that men should benefit one another.","Marcus Aurelius, Meditations 9.42","Stoic"],
[14,"There was never a benevolent man who neglected his parents; there was never a righteous man who put his sovereign last.","Mencius 1A1","Confucian"],
[15,"It is a poor service that is rendered under compulsion.","Publilius Syrus, Sentences","Roman"],
[16,"Heaven does not suspend winter because men dislike cold.","Xunzi","Confucian"],
[17,"Nothing is more noble, nothing more venerable, than fidelity.","Cicero, De Officiis","Roman"],
[18,"The people are the most important element in a nation; the sovereign is the lightest.","Mencius 7B14","Confucian"],
[19,"Such as are your habitual acts, such also will be the character of your life.","Marcus Aurelius, Meditations 5.1","Stoic"],
[20,"A benefit consists not in what is done, but in the intention of the giver.","Seneca, De Beneficiis","Stoic"],
[21,"Lead the people by virtue and regulate them by the rules of propriety, and they will have a sense of shame, and moreover become good.","Confucius, Analects 2.3","Confucian"],
[22,"As men we are all equal in the presence of death.","Publilius Syrus, Sentences","Roman"],
[23,"Men are indeed created for the sake of one another.","Cicero, De Officiis 1.20","Roman"],
[24,"When one by force subdues men, they do not submit in heart.","Mencius 2A3","Confucian"],
[25,"Rites are the great basis on which to accord with what is fitting.","Xunzi","Confucian"],
[26,"If reason is common to all men, so also is law; and if this is so, we are fellow citizens of one political community.","Marcus Aurelius, Meditations 4.4","Stoic"],
[27,"Let the ruler be a ruler, the minister a minister, the father a father, the son a son.","Confucius, Analects 12.11","Confucian"],
[28,"Man is a thing sacred to man.","Seneca, Letters 95","Stoic"],
[29,"One generation plants the trees; another gets the shade.","Chinese proverb","Chinese"],
[30,"We are not born for ourselves alone; our country claims a share of us, and our friends a share.","Cicero, De Officiis","Roman"],
],
10:[
[1,"Nowhere can a man find a quieter or more untroubled retreat than in his own soul.","Marcus Aurelius, Meditations 4.3","Stoic"],
[2,"Attain complete emptiness; maintain steadfast stillness.","Laozi, Tao Te Ching 16","Taoist"],
[3,"Emptiness, stillness, tranquility, silence, inaction — these are the level of Heaven and Earth.","Zhuangzi, The Way of Heaven","Taoist"],
[4,"Be silent, or say something better than silence.","Attributed to Pythagoras","Greek"],
[5,"Let silence be your general rule; or say only what is necessary and in few words.","Epictetus, Enchiridion 33","Stoic"],
[6,"Stillness is the ruler of restlessness.","Laozi, Tao Te Ching 26","Taoist"],
[7,"How easy it is to repel every impression which is troublesome, and immediately to be in perfect tranquility.","Marcus Aurelius, Meditations 5.2","Stoic"],
[8,"The mind ought sometimes to be diverted, that it may return to better thinking.","Seneca, De Tranquillitate Animi","Stoic"],
[9,"The still mind of the sage is the mirror of heaven and earth.","Zhuangzi, The Way of Heaven","Taoist"],
[10,"The quieter you become, the more you are able to hear.","Proverb","Wisdom"],
[11,"Who can wait quietly while the mud settles? Who can remain still until the moment of action?","Laozi, Tao Te Ching 15","Taoist"],
[12,"When you have been forced by circumstances to be disturbed, quickly return to yourself.","Marcus Aurelius, Meditations 6.11","Stoic"],
[13,"The condition and characteristic of a philosopher is that he expects all advantage and all harm from himself.","Epictetus, Enchiridion 48","Stoic"],
[14,"Water is the most soft and weak of all things, and yet it can wear away the hardest, precisely because it is yielding.","Zhuangzi, tradition","Taoist"],
[15,"The Tao never acts, yet nothing is left undone.","Laozi, Tao Te Ching 37","Taoist"],
[16,"It is the disease of the mind, not of the place, that troubles us.","Seneca, Letters 56","Stoic"],
[17,"To do good and to be calm — that is enough.","Marcus Aurelius, Meditations 9.6","Stoic"],
[18,"In a calm sea every man is a pilot.","Proverb","Wisdom"],
[19,"The sage's stillness is not because stillness is considered good; it is because the ten thousand things cannot disturb him.","Zhuangzi, The Way of Heaven","Taoist"],
[20,"Remember that it is not he who reviles you that insults you, but your own opinion that such things are insulting.","Epictetus, Enchiridion 20","Stoic"],
[21,"Use the light that is within you to regain your natural clearness of sight.","Laozi, Tao Te Ching 52","Taoist"],
[22,"Retire into yourself. The rational principle which rules is content with itself when it does what is just.","Marcus Aurelius, Meditations 7.28","Stoic"],
[23,"Forget the years, forget distinctions. Leap into the boundless and make it your home.","Zhuangzi, Discussion on Making All Things Equal","Taoist"],
[24,"Silence is also a kind of answer.","Japanese proverb","Japanese"],
[25,"It is in your power to withdraw yourself whenever you desire. Perfect tranquility is within.","Marcus Aurelius, Meditations 9.32","Stoic"],
[26,"Without going outside, you may know the whole world. Without looking through the window, you may see the ways of heaven.","Laozi, Tao Te Ching 47","Taoist"],
[27,"No one is free who has not obtained the empire of himself.","Attributed to Pythagoras","Greek"],
[28,"Sit down and forget everything.","Zhuangzi, The Great Teacher","Taoist"],
[29,"Until we have begun to go without them, we fail to realize how unnecessary many things are; we have been using them not because we needed them, but because we had them.","Seneca, Letters 4","Stoic"],
[30,"Though the Tao is small in the unformed state, it can subdue the world.","Laozi, Tao Te Ching 32","Taoist"],
[31,"Give yourself time to learn something new and good, and cease to be whirled around.","Marcus Aurelius, Meditations 2.7","Stoic"],
],
11:[
[1,"In every case rejoice at whatever comes to pass, taking into account the connection of causes.","Marcus Aurelius, Meditations 12.29","Stoic"],
[2,"He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.","Epictetus","Stoic"],
[3,"Give thanks in all circumstances; this is what is expected of you.","Marcus Aurelius, tradition","Stoic"],
[4,"Gratitude is not only the greatest of virtues, but the parent of all the others.","Cicero","Roman"],
[5,"When you drink water, remember the spring.","Chinese proverb","Chinese"],
[6,"Do not spoil what you have by desiring what you have not.","Epicurus","Greek"],
[7,"This is the day; let us make the most of it, for it will never come again.","Proverb","Wisdom"],
[8,"Whoever does not thank people has not truly valued the gift.","Proverb","Wisdom"],
[9,"Think of yourself as dead. You have lived your life. Now take what is left and live it properly.","Marcus Aurelius, Meditations 7.56","Stoic"],
[10,"Friendship makes prosperity more shining, and lessens adversity by dividing and sharing it.","Cicero, De Amicitia","Roman"],
[11,"Memento mori — remember that you must die, and let the remembering teach you to live.","Roman practice","Stoic"],
[12,"Death twitches my ear. 'Live,' he says; 'I am coming.'","Virgil","Roman"],
[13,"Let us prepare our minds as if we had come to the very end of life. Let us postpone nothing.","Seneca, Letters 101","Stoic"],
[14,"He who is not contented with what he has would not be contented with what he would like to have.","Attributed to Socrates","Greek"],
[15,"Consider that before long you will be nobody and nowhere.","Marcus Aurelius, Meditations 12.31","Stoic"],
[16,"It is not the man who has too little, but the man who craves more, that is poor.","Seneca, Letters 2","Stoic"],
[17,"Remember that you must behave in life as if at a banquet. A dish is offered you; put out your hand and take a portion with moderation. Does it pass by you? Do not stop it.","Epictetus, Enchiridion 15","Stoic"],
[18,"Man, you have been a citizen in this great city; what does it matter if for five years or a hundred?","Marcus Aurelius, Meditations 12.36","Stoic"],
[19,"A grateful heart finds occasion for thanksgiving in every event.","Proverb","Wisdom"],
[20,"Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.","Proverb","Wisdom"],
[21,"Gratitude turns the little we have into an abundance.","Proverb","Wisdom"],
[22,"As physicians have always their instruments ready for cases which suddenly require their skill, have your principles ready.","Marcus Aurelius, Meditations 3.13","Stoic"],
[23,"The fear of losing what we have often blinds us to the gladness of already having it.","Seneca, tradition","Stoic"],
[24,"Wherever you look, there is one and the same nature, one and the same substance.","Marcus Aurelius, Meditations 4.40","Stoic"],
[25,"Reflect upon your present blessings, of which every man has plenty.","Proverb","Wisdom"],
[26,"So teach us to number our days that we may get a heart of wisdom.","Proverb, ancient wisdom tradition","Wisdom","Psalm 90:12, travelling anonymously for centuries. Named here so the tag is honest; the psalm itself lives in the Library."],
[27,"Nothing is enough for the man to whom enough is too little.","Epicurus","Greek"],
[28,"A cheerful giver is thanked twice — once for the gift, once for the spirit in which it was given.","Proverb","Wisdom"],
[29,"To be able to enjoy one's past life is to live twice.","Cicero","Roman"],
[30,"When the cold season comes, then we know how the pine and the cypress are the last to lose their leaves.","Confucius, Analects 9.28","Confucian"],
],
12:[
[1,"However long the night, the dawn will break.","African proverb","African"],
[2,"The seasons come and go, and nothing stays; the sage flows with the transformation.","Zhuangzi, tradition","Taoist"],
[3,"If a man in the morning attains to the truth, he may die in the evening without regret.","Confucius, Analects 4.8","Confucian"],
[4,"Hope is the last thing kept at the bottom of the jar.","Greek tradition, myth of Pandora","Greek"],
[5,"Adapt yourself to the things among which your lot has been cast, and love sincerely the fellow creatures with whom destiny has ordained that you shall live.","Marcus Aurelius, Meditations 6.39","Stoic"],
[6,"Hope is often better than the actual enjoyment.","Publilius Syrus, Sentences","Roman"],
[7,"Whatever may happen to you was prepared for you from all eternity.","Marcus Aurelius, Meditations 10.5","Stoic"],
[8,"The light returns; it always has. Keep the lamp trimmed while you wait.","Proverb, winter solstice tradition","Wisdom"],
[9,"The morning mushroom knows not the alternation of day and night; the summer cicada knows not the seasons of spring and autumn — yet the seasons turn all the same.","Zhuangzi, Free and Easy Wandering","Taoist"],
[10,"While there's life, there's hope.","Cicero, tradition","Roman"],
[11,"Can you remain unmoving until the right action arises by itself?","Laozi, Tao Te Ching 15","Taoist"],
[12,"He who overcomes others is strong; he who overcomes himself is mighty.","Tao Te Ching 33, Legge","Taoist"],
[13,"Blue dye is extracted from the indigo plant, yet it is bluer than the plant it comes from.","Xunzi, Encouraging Learning","Confucian"],
[14,"As long as you are ignorant of what to aim at, the whole world seems adverse to you; but the moment your purpose is fixed, all things seem to fall in with your design.","Seneca, Letters 71","Stoic"],
[15,"The darkest hour has only sixty minutes.","Proverb","Wisdom"],
[16,"Observe constantly that all things take place by change, and accustom yourself to consider that the nature of the universe loves nothing so much as to change existing things and make new things like them.","Marcus Aurelius, Meditations 4.36","Stoic"],
[17,"Man's nature is naturally good, just as water naturally flows downward.","Mencius 6A2","Confucian"],
[18,"Easy is right. Begin right and you are easy; continue easy and you are right.","Zhuangzi, Fitting Everything to Its Own Right","Taoist"],
[19,"Hope is the pillar that holds up the world.","Pliny the Elder, tradition","Roman"],
[20,"The seed already sleeps in the ground, waiting for its hour.","Proverb, winter tradition","Wisdom"],
[21,"It is in adversity that virtue reveals itself most completely.","Seneca, tradition","Stoic"],
[22,"The Tao produced One; One produced Two; Two produced Three; Three produced All Things.","Laozi, Tao Te Ching 42","Taoist"],
[23,"After the darkest night, the sun rises as if nothing had happened.","Persian saying","Persian"],
[24,"Though the road be short, without walking you cannot arrive.","Xunzi","Confucian"],
[25,"Think of the virtues of those who live with you; for the sight of virtue is most delightful.","Marcus Aurelius, Meditations 6.48","Stoic"],
[26,"Learning extensively, and having a firm and sincere aim; inquiring with earnestness, and reflecting with self-application — virtue is in such a course.","Confucius, Analects 19.6","Confucian"],
[27,"Many things unforeseen befall the man who hopes.","Publilius Syrus, Sentences","Roman"],
[28,"The nature of the universe, out of its own substance, molds a horse, then melts the figure down, and uses the material for a tree, then for something else.","Marcus Aurelius, Meditations 4.36","Stoic"],
[29,"Does Heaven speak? The four seasons pursue their courses, and all things are continually being produced — yet does Heaven say anything?","Confucius, Analects 17.19","Confucian"],
[30,"Set aside a certain number of days during which you shall be content with the scantiest fare — then ask yourself: is this the condition I feared?","Seneca, Letters 18","Stoic"],
[31,"Without recognizing the ordinances of Heaven, it is impossible to be a superior man.","Confucius, Analects 20.3","Confucian"],
],
};
