/* First Light — the library index.

   Generated by .scripts/build-library.js from the baked texts. Do not edit by hand;
   re-run the generator instead.

   Small on purpose: this is precached with the app shell so the Library can show
   every work, book and chapter offline, before any scripture is loaded. The text
   itself lives in js/texts/<work>/<part>.js and loads only when a passage is opened.
   Total library on disk: 10.57 MB. */

var FL_LIBRARY = {
 "rigveda": {
  "title": "The Rig Veda",
  "translation": "Ralph T. H. Griffith, 1896",
  "license": "Public domain",
  "source": "Wikisource",
  "bytes": 1707378,
  "parts": [
   {
    "part": "01",
    "mandala": 1,
    "hymns": 191
   },
   {
    "part": "02",
    "mandala": 2,
    "hymns": 43
   },
   {
    "part": "03",
    "mandala": 3,
    "hymns": 62
   },
   {
    "part": "04",
    "mandala": 4,
    "hymns": 58
   },
   {
    "part": "05",
    "mandala": 5,
    "hymns": 87
   },
   {
    "part": "06",
    "mandala": 6,
    "hymns": 75
   },
   {
    "part": "07",
    "mandala": 7,
    "hymns": 104
   },
   {
    "part": "08",
    "mandala": 8,
    "hymns": 103
   },
   {
    "part": "09",
    "mandala": 9,
    "hymns": 114
   },
   {
    "part": "10",
    "mandala": 10,
    "hymns": 191
   }
  ]
 },
 "tanakh": {
  "title": "The Hebrew Bible",
  "translation": "The Holy Scriptures: A New Translation (JPS 1917)",
  "license": "Public domain",
  "source": "Sefaria",
  "bytes": 3281207,
  "parts": [
   {
    "part": "01",
    "book": "Genesis",
    "section": "Torah",
    "chapters": 50,
    "bytes": 204269
   },
   {
    "part": "02",
    "book": "Exodus",
    "section": "Torah",
    "chapters": 40,
    "bytes": 173796
   },
   {
    "part": "03",
    "book": "Leviticus",
    "section": "Torah",
    "chapters": 27,
    "bytes": 128560
   },
   {
    "part": "04",
    "book": "Numbers",
    "section": "Torah",
    "chapters": 36,
    "bytes": 179382
   },
   {
    "part": "05",
    "book": "Deuteronomy",
    "section": "Torah",
    "chapters": 34,
    "bytes": 149760
   },
   {
    "part": "06",
    "book": "Joshua",
    "section": "Prophets",
    "chapters": 24,
    "bytes": 103446
   },
   {
    "part": "07",
    "book": "Judges",
    "section": "Prophets",
    "chapters": 21,
    "bytes": 101864
   },
   {
    "part": "08",
    "book": "I Samuel",
    "section": "Prophets",
    "chapters": 31,
    "bytes": 133970
   },
   {
    "part": "09",
    "book": "II Samuel",
    "section": "Prophets",
    "chapters": 24,
    "bytes": 110338
   },
   {
    "part": "10",
    "book": "I Kings",
    "section": "Prophets",
    "chapters": 22,
    "bytes": 130844
   },
   {
    "part": "11",
    "book": "II Kings",
    "section": "Prophets",
    "chapters": 25,
    "bytes": 124604
   },
   {
    "part": "12",
    "book": "Isaiah",
    "section": "Prophets",
    "chapters": 66,
    "bytes": 197198
   },
   {
    "part": "13",
    "book": "Jeremiah",
    "section": "Prophets",
    "chapters": 52,
    "bytes": 228202
   },
   {
    "part": "14",
    "book": "Ezekiel",
    "section": "Prophets",
    "chapters": 48,
    "bytes": 209279
   },
   {
    "part": "15",
    "book": "Hosea",
    "section": "Prophets",
    "chapters": 14,
    "bytes": 28009
   },
   {
    "part": "16",
    "book": "Joel",
    "section": "Prophets",
    "chapters": 4,
    "bytes": 10937
   },
   {
    "part": "17",
    "book": "Amos",
    "section": "Prophets",
    "chapters": 9,
    "bytes": 22093
   },
   {
    "part": "18",
    "book": "Obadiah",
    "section": "Prophets",
    "chapters": 1,
    "bytes": 3629
   },
   {
    "part": "19",
    "book": "Jonah",
    "section": "Prophets",
    "chapters": 4,
    "bytes": 7036
   },
   {
    "part": "20",
    "book": "Micah",
    "section": "Prophets",
    "chapters": 7,
    "bytes": 16861
   },
   {
    "part": "21",
    "book": "Nahum",
    "section": "Prophets",
    "chapters": 3,
    "bytes": 6969
   },
   {
    "part": "22",
    "book": "Habakkuk",
    "section": "Prophets",
    "chapters": 3,
    "bytes": 8074
   },
   {
    "part": "23",
    "book": "Zephaniah",
    "section": "Prophets",
    "chapters": 3,
    "bytes": 8807
   },
   {
    "part": "24",
    "book": "Haggai",
    "section": "Prophets",
    "chapters": 2,
    "bytes": 6014
   },
   {
    "part": "25",
    "book": "Zechariah",
    "section": "Prophets",
    "chapters": 14,
    "bytes": 33999
   },
   {
    "part": "26",
    "book": "Malachi",
    "section": "Prophets",
    "chapters": 3,
    "bytes": 9605
   },
   {
    "part": "27",
    "book": "Psalms",
    "section": "Writings",
    "chapters": 150,
    "bytes": 235047
   },
   {
    "part": "28",
    "book": "Proverbs",
    "section": "Writings",
    "chapters": 31,
    "bytes": 83038
   },
   {
    "part": "29",
    "book": "Job",
    "section": "Writings",
    "chapters": 42,
    "bytes": 98091
   },
   {
    "part": "30",
    "book": "Song of Songs",
    "section": "Writings",
    "chapters": 8,
    "bytes": 14161
   },
   {
    "part": "31",
    "book": "Ruth",
    "section": "Writings",
    "chapters": 4,
    "bytes": 13645
   },
   {
    "part": "32",
    "book": "Lamentations",
    "section": "Writings",
    "chapters": 5,
    "bytes": 18751
   },
   {
    "part": "33",
    "book": "Ecclesiastes",
    "section": "Writings",
    "chapters": 12,
    "bytes": 29308
   },
   {
    "part": "34",
    "book": "Esther",
    "section": "Writings",
    "chapters": 10,
    "bytes": 31349
   },
   {
    "part": "35",
    "book": "Daniel",
    "section": "Writings",
    "chapters": 12,
    "bytes": 63944
   },
   {
    "part": "36",
    "book": "Ezra",
    "section": "Writings",
    "chapters": 10,
    "bytes": 41287
   },
   {
    "part": "37",
    "book": "Nehemiah",
    "section": "Writings",
    "chapters": 13,
    "bytes": 58425
   },
   {
    "part": "38",
    "book": "I Chronicles",
    "section": "Writings",
    "chapters": 29,
    "bytes": 114105
   },
   {
    "part": "39",
    "book": "II Chronicles",
    "section": "Writings",
    "chapters": 36,
    "bytes": 142511
   }
  ]
 },
 "upanishads": {
  "title": "Three Upanishads",
  "translation": "Swami Paramananda — Isa, Katha and Kena, with his commentary",
  "license": "Public domain",
  "source": "Project Gutenberg",
  "bytes": 94009,
  "parts": [
   {
    "part": "all"
   }
  ],
  "chapters": [
   {
    "n": 1,
    "title": "Isa-Upanishad",
    "blocks": 64
   },
   {
    "n": 2,
    "title": "Katha-Upanishad",
    "blocks": 310
   },
   {
    "n": 3,
    "title": "Kena-Upanishad",
    "blocks": 103
   }
  ]
 },
 "dhammapada": {
  "title": "The Dhammapada",
  "translation": "F. Max Müller, 1881",
  "license": "Public domain",
  "source": "Project Gutenberg",
  "bytes": 66650,
  "parts": [
   {
    "part": "all"
   }
  ],
  "chapters": [
   {
    "title": "The Twin-Verses",
    "verses": 20
   },
   {
    "title": "On Earnestness",
    "verses": 12
   },
   {
    "title": "Thought",
    "verses": 11
   },
   {
    "title": "Flowers",
    "verses": 15
   },
   {
    "title": "The Fool",
    "verses": 16
   },
   {
    "title": "The Wise Man (Pandita)",
    "verses": 13
   },
   {
    "title": "The Venerable (Arhat)",
    "verses": 10
   },
   {
    "title": "The Thousands",
    "verses": 15
   },
   {
    "title": "Evil",
    "verses": 13
   },
   {
    "title": "Punishment",
    "verses": 17
   },
   {
    "title": "Old Age",
    "verses": 10
   },
   {
    "title": "Self",
    "verses": 10
   },
   {
    "title": "The World",
    "verses": 12
   },
   {
    "title": "The Buddha (The Awakened)",
    "verses": 17
   },
   {
    "title": "Happiness",
    "verses": 12
   },
   {
    "title": "Pleasure",
    "verses": 12
   },
   {
    "title": "Anger",
    "verses": 13
   },
   {
    "title": "Impurity",
    "verses": 21
   },
   {
    "title": "The Just",
    "verses": 14
   },
   {
    "title": "The Way",
    "verses": 17
   },
   {
    "title": "Miscellaneous",
    "verses": 16
   },
   {
    "title": "The Downward Course",
    "verses": 14
   },
   {
    "title": "The Elephant",
    "verses": 14
   },
   {
    "title": "Thirst",
    "verses": 26
   },
   {
    "title": "The Bhikshu (Mendicant)",
    "verses": 23
   },
   {
    "title": "The Brahmana (Arhat)",
    "verses": 41
   }
  ]
 },
 "analects": {
  "title": "The Analects",
  "translation": "James Legge, 1893",
  "license": "Public domain",
  "source": "Project Gutenberg",
  "bytes": 169890,
  "parts": [
   {
    "part": "all"
   }
  ],
  "chapters": [
   {
    "n": 1,
    "title": "HSIO R.",
    "chapters": 16
   },
   {
    "n": 2,
    "title": "WEI CHANG.",
    "chapters": 24
   },
   {
    "n": 3,
    "title": "PA YIH.",
    "chapters": 26
   },
   {
    "n": 4,
    "title": "LE JIN.",
    "chapters": 26
   },
   {
    "n": 5,
    "title": "KUNG-YE CH'ANG.",
    "chapters": 27
   },
   {
    "n": 6,
    "title": "YUNG YEY.",
    "chapters": 28
   },
   {
    "n": 7,
    "title": "SHU R.",
    "chapters": 36
   },
   {
    "n": 8,
    "title": "T'AI-PO.",
    "chapters": 21
   },
   {
    "n": 9,
    "title": "TSZE HAN.",
    "chapters": 30
   },
   {
    "n": 10,
    "title": "HEANG TANG.",
    "chapters": 18
   },
   {
    "n": 11,
    "title": "HSIEN TSIN.",
    "chapters": 25
   },
   {
    "n": 12,
    "title": "YEN YUAN.",
    "chapters": 24
   },
   {
    "n": 13,
    "title": "TSZE-LU.",
    "chapters": 30
   },
   {
    "n": 14,
    "title": "HSIEN WAN.",
    "chapters": 47
   },
   {
    "n": 15,
    "title": "WEI LING KUNG.",
    "chapters": 41
   },
   {
    "n": 16,
    "title": "KE SHE.",
    "chapters": 14
   },
   {
    "n": 17,
    "title": "YANG HO.",
    "chapters": 26
   },
   {
    "n": 18,
    "title": "WEI TSZE.",
    "chapters": 11
   },
   {
    "n": 19,
    "title": "TSZE-CHANG.",
    "chapters": 25
   },
   {
    "n": 20,
    "title": "YAO YUEH.",
    "chapters": 3
   }
  ]
 },
 "tao": {
  "title": "The Tao Te Ching",
  "translation": "James Legge, 1891",
  "license": "Public domain",
  "source": "Project Gutenberg",
  "bytes": 61562,
  "parts": [
   {
    "part": "all"
   }
  ],
  "chapters": [
   {
    "n": 1,
    "blocks": 5
   },
   {
    "n": 2,
    "blocks": 5
   },
   {
    "n": 3,
    "blocks": 3
   },
   {
    "n": 4,
    "blocks": 3
   },
   {
    "n": 5,
    "blocks": 3
   },
   {
    "n": 6,
    "blocks": 1
   },
   {
    "n": 7,
    "blocks": 2
   },
   {
    "n": 8,
    "blocks": 3
   },
   {
    "n": 9,
    "blocks": 2
   },
   {
    "n": 10,
    "blocks": 3
   },
   {
    "n": 11,
    "blocks": 1
   },
   {
    "n": 12,
    "blocks": 3
   },
   {
    "n": 13,
    "blocks": 4
   },
   {
    "n": 14,
    "blocks": 3
   },
   {
    "n": 15,
    "blocks": 4
   },
   {
    "n": 16,
    "blocks": 2
   },
   {
    "n": 17,
    "blocks": 2
   },
   {
    "n": 18,
    "blocks": 2
   },
   {
    "n": 19,
    "blocks": 3
   },
   {
    "n": 20,
    "blocks": 5
   },
   {
    "n": 21,
    "blocks": 2
   },
   {
    "n": 22,
    "blocks": 3
   },
   {
    "n": 23,
    "blocks": 3
   },
   {
    "n": 24,
    "blocks": 1
   },
   {
    "n": 25,
    "blocks": 4
   },
   {
    "n": 26,
    "blocks": 2
   },
   {
    "n": 27,
    "blocks": 2
   },
   {
    "n": 28,
    "blocks": 5
   },
   {
    "n": 29,
    "blocks": 4
   },
   {
    "n": 30,
    "blocks": 4
   },
   {
    "n": 31,
    "blocks": 3
   },
   {
    "n": 32,
    "blocks": 5
   },
   {
    "n": 33,
    "blocks": 2
   },
   {
    "n": 34,
    "blocks": 3
   },
   {
    "n": 35,
    "blocks": 2
   },
   {
    "n": 36,
    "blocks": 3
   },
   {
    "n": 37,
    "blocks": 5
   },
   {
    "n": 38,
    "blocks": 7
   },
   {
    "n": 39,
    "blocks": 6
   },
   {
    "n": 40,
    "blocks": 3
   },
   {
    "n": 41,
    "blocks": 4
   },
   {
    "n": 42,
    "blocks": 3
   },
   {
    "n": 43,
    "blocks": 2
   },
   {
    "n": 44,
    "blocks": 6
   },
   {
    "n": 45,
    "blocks": 3
   },
   {
    "n": 46,
    "blocks": 2
   },
   {
    "n": 47,
    "blocks": 2
   },
   {
    "n": 48,
    "blocks": 3
   },
   {
    "n": 49,
    "blocks": 3
   },
   {
    "n": 50,
    "blocks": 4
   },
   {
    "n": 51,
    "blocks": 4
   },
   {
    "n": 52,
    "blocks": 6
   },
   {
    "n": 53,
    "blocks": 3
   },
   {
    "n": 54,
    "blocks": 6
   },
   {
    "n": 55,
    "blocks": 5
   },
   {
    "n": 56,
    "blocks": 3
   },
   {
    "n": 57,
    "blocks": 3
   },
   {
    "n": 58,
    "blocks": 5
   },
   {
    "n": 59,
    "blocks": 3
   },
   {
    "n": 60,
    "blocks": 3
   },
   {
    "n": 61,
    "blocks": 4
   },
   {
    "n": 62,
    "blocks": 5
   },
   {
    "n": 63,
    "blocks": 3
   },
   {
    "n": 64,
    "blocks": 4
   },
   {
    "n": 65,
    "blocks": 3
   },
   {
    "n": 66,
    "blocks": 3
   },
   {
    "n": 67,
    "blocks": 4
   },
   {
    "n": 68,
    "blocks": 2
   },
   {
    "n": 69,
    "blocks": 2
   },
   {
    "n": 70,
    "blocks": 3
   },
   {
    "n": 71,
    "blocks": 2
   },
   {
    "n": 72,
    "blocks": 4
   },
   {
    "n": 73,
    "blocks": 4
   },
   {
    "n": 74,
    "blocks": 2
   },
   {
    "n": 75,
    "blocks": 3
   },
   {
    "n": 76,
    "blocks": 4
   },
   {
    "n": 77,
    "blocks": 4
   },
   {
    "n": 78,
    "blocks": 5
   },
   {
    "n": 79,
    "blocks": 3
   },
   {
    "n": 80,
    "blocks": 5
   },
   {
    "n": 81,
    "blocks": 3
   }
  ]
 },
 "zhuangzi": {
  "title": "The Zhuangzi",
  "translation": "Herbert A. Giles, 1889",
  "license": "Public domain",
  "source": "Project Gutenberg",
  "bytes": 623146,
  "parts": [
   {
    "part": "all"
   }
  ],
  "chapters": [
   {
    "n": 1,
    "blocks": 73
   },
   {
    "n": 2,
    "blocks": 156
   },
   {
    "n": 3,
    "blocks": 28
   },
   {
    "n": 4,
    "blocks": 117
   },
   {
    "n": 5,
    "blocks": 75
   },
   {
    "n": 6,
    "blocks": 215
   },
   {
    "n": 7,
    "blocks": 72
   },
   {
    "n": 8,
    "blocks": 40
   },
   {
    "n": 9,
    "blocks": 25
   },
   {
    "n": 10,
    "blocks": 62
   },
   {
    "n": 11,
    "blocks": 129
   },
   {
    "n": 12,
    "blocks": 158
   },
   {
    "n": 13,
    "blocks": 108
   },
   {
    "n": 14,
    "blocks": 140
   },
   {
    "n": 15,
    "blocks": 38
   },
   {
    "n": 16,
    "blocks": 37
   },
   {
    "n": 17,
    "blocks": 153
   },
   {
    "n": 18,
    "blocks": 65
   },
   {
    "n": 19,
    "blocks": 133
   },
   {
    "n": 20,
    "blocks": 128
   },
   {
    "n": 21,
    "blocks": 142
   },
   {
    "n": 22,
    "blocks": 171
   },
   {
    "n": 23,
    "blocks": 152
   },
   {
    "n": 24,
    "blocks": 235
   },
   {
    "n": 25,
    "blocks": 149
   },
   {
    "n": 26,
    "blocks": 97
   },
   {
    "n": 27,
    "blocks": 57
   },
   {
    "n": 28,
    "blocks": 136
   },
   {
    "n": 29,
    "blocks": 138
   },
   {
    "n": 30,
    "blocks": 44
   },
   {
    "n": 31,
    "blocks": 67
   },
   {
    "n": 32,
    "blocks": 124
   },
   {
    "n": 33,
    "blocks": 1073
   }
  ]
 },
 "gita": {
  "title": "The Bhagavad Gita",
  "translation": "Sir Edwin Arnold, 1885",
  "license": "Public domain",
  "source": "Project Gutenberg",
  "bytes": 119198,
  "parts": [
   {
    "part": "all"
   }
  ],
  "chapters": [
   {
    "n": 1,
    "blocks": 9
   },
   {
    "n": 2,
    "blocks": 20
   },
   {
    "n": 3,
    "blocks": 7
   },
   {
    "n": 4,
    "blocks": 6
   },
   {
    "n": 5,
    "blocks": 6
   },
   {
    "n": 6,
    "blocks": 13
   },
   {
    "n": 7,
    "blocks": 11
   },
   {
    "n": 8,
    "blocks": 13
   },
   {
    "n": 9,
    "blocks": 18
   },
   {
    "n": 10,
    "blocks": 4
   },
   {
    "n": 11,
    "blocks": 50
   },
   {
    "n": 12,
    "blocks": 5
   },
   {
    "n": 13,
    "blocks": 13
   },
   {
    "n": 14,
    "blocks": 12
   },
   {
    "n": 15,
    "blocks": 16
   },
   {
    "n": 16,
    "blocks": 9
   },
   {
    "n": 17,
    "blocks": 14
   },
   {
    "n": 18,
    "blocks": 69
   }
  ]
 },
 "bible": {
  "title": "The Bible",
  "translation": "World English Bible",
  "license": "Public domain",
  "source": "getbible.net",
  "bytes": 4105997,
  "parts": [
   {
    "part": "01",
    "book": "Genesis",
    "chapters": 50,
    "bytes": 193423
   },
   {
    "part": "02",
    "book": "Exodus",
    "chapters": 40,
    "bytes": 165162
   },
   {
    "part": "03",
    "book": "Leviticus",
    "chapters": 27,
    "bytes": 124355
   },
   {
    "part": "04",
    "book": "Numbers",
    "chapters": 36,
    "bytes": 170813
   },
   {
    "part": "05",
    "book": "Deuteronomy",
    "chapters": 34,
    "bytes": 143129
   },
   {
    "part": "06",
    "book": "Joshua",
    "chapters": 24,
    "bytes": 97157
   },
   {
    "part": "07",
    "book": "Judges",
    "chapters": 21,
    "bytes": 97451
   },
   {
    "part": "08",
    "book": "Ruth",
    "chapters": 4,
    "bytes": 13093
   },
   {
    "part": "09",
    "book": "1 Samuel",
    "chapters": 31,
    "bytes": 127811
   },
   {
    "part": "10",
    "book": "2 Samuel",
    "chapters": 24,
    "bytes": 105485
   },
   {
    "part": "11",
    "book": "1 Kings",
    "chapters": 22,
    "bytes": 124785
   },
   {
    "part": "12",
    "book": "2 Kings",
    "chapters": 25,
    "bytes": 119781
   },
   {
    "part": "13",
    "book": "1 Chronicles",
    "chapters": 29,
    "bytes": 111141
   },
   {
    "part": "14",
    "book": "2 Chronicles",
    "chapters": 36,
    "bytes": 137806
   },
   {
    "part": "15",
    "book": "Ezra",
    "chapters": 10,
    "bytes": 40066
   },
   {
    "part": "16",
    "book": "Nehemiah",
    "chapters": 13,
    "bytes": 56733
   },
   {
    "part": "17",
    "book": "Esther",
    "chapters": 10,
    "bytes": 29900
   },
   {
    "part": "18",
    "book": "Job",
    "chapters": 42,
    "bytes": 94674
   },
   {
    "part": "19",
    "book": "Psalms",
    "chapters": 150,
    "bytes": 220969
   },
   {
    "part": "20",
    "book": "Proverbs",
    "chapters": 31,
    "bytes": 79304
   },
   {
    "part": "21",
    "book": "Ecclesiastes",
    "chapters": 12,
    "bytes": 28433
   },
   {
    "part": "22",
    "book": "Song of Songs",
    "chapters": 8,
    "bytes": 13805
   },
   {
    "part": "23",
    "book": "Isaiah",
    "chapters": 66,
    "bytes": 192092
   },
   {
    "part": "24",
    "book": "Jeremiah",
    "chapters": 52,
    "bytes": 222149
   },
   {
    "part": "25",
    "book": "Lamentations",
    "chapters": 5,
    "bytes": 18195
   },
   {
    "part": "26",
    "book": "Ezekiel",
    "chapters": 48,
    "bytes": 202625
   },
   {
    "part": "27",
    "book": "Daniel",
    "chapters": 12,
    "bytes": 61645
   },
   {
    "part": "28",
    "book": "Hosea",
    "chapters": 14,
    "bytes": 27438
   },
   {
    "part": "29",
    "book": "Joel",
    "chapters": 3,
    "bytes": 10581
   },
   {
    "part": "30",
    "book": "Amos",
    "chapters": 9,
    "bytes": 21858
   },
   {
    "part": "31",
    "book": "Obadiah",
    "chapters": 1,
    "bytes": 3421
   },
   {
    "part": "32",
    "book": "Jonah",
    "chapters": 4,
    "bytes": 6699
   },
   {
    "part": "33",
    "book": "Micah",
    "chapters": 7,
    "bytes": 16021
   },
   {
    "part": "34",
    "book": "Nahum",
    "chapters": 3,
    "bytes": 6687
   },
   {
    "part": "35",
    "book": "Habakkuk",
    "chapters": 3,
    "bytes": 7597
   },
   {
    "part": "36",
    "book": "Zephaniah",
    "chapters": 3,
    "bytes": 8478
   },
   {
    "part": "37",
    "book": "Haggai",
    "chapters": 2,
    "bytes": 5753
   },
   {
    "part": "38",
    "book": "Zechariah",
    "chapters": 14,
    "bytes": 32494
   },
   {
    "part": "39",
    "book": "Malachi",
    "chapters": 4,
    "bytes": 9332
   },
   {
    "part": "40",
    "book": "Matthew",
    "chapters": 28,
    "bytes": 125598
   },
   {
    "part": "41",
    "book": "Mark",
    "chapters": 16,
    "bytes": 78755
   },
   {
    "part": "42",
    "book": "Luke",
    "chapters": 24,
    "bytes": 133341
   },
   {
    "part": "43",
    "book": "John",
    "chapters": 21,
    "bytes": 100908
   },
   {
    "part": "44",
    "book": "Acts",
    "chapters": 28,
    "bytes": 128522
   },
   {
    "part": "45",
    "book": "Romans",
    "chapters": 16,
    "bytes": 51610
   },
   {
    "part": "46",
    "book": "1 Corinthians",
    "chapters": 16,
    "bytes": 50206
   },
   {
    "part": "47",
    "book": "2 Corinthians",
    "chapters": 13,
    "bytes": 32765
   },
   {
    "part": "48",
    "book": "Galatians",
    "chapters": 6,
    "bytes": 16883
   },
   {
    "part": "49",
    "book": "Ephesians",
    "chapters": 6,
    "bytes": 16880
   },
   {
    "part": "50",
    "book": "Philippians",
    "chapters": 4,
    "bytes": 11919
   },
   {
    "part": "51",
    "book": "Colossians",
    "chapters": 4,
    "bytes": 11071
   },
   {
    "part": "52",
    "book": "1 Thessalonians",
    "chapters": 5,
    "bytes": 9969
   },
   {
    "part": "53",
    "book": "2 Thessalonians",
    "chapters": 3,
    "bytes": 5642
   },
   {
    "part": "54",
    "book": "1 Timothy",
    "chapters": 6,
    "bytes": 13108
   },
   {
    "part": "55",
    "book": "2 Timothy",
    "chapters": 4,
    "bytes": 9177
   },
   {
    "part": "56",
    "book": "Titus",
    "chapters": 3,
    "bytes": 5350
   },
   {
    "part": "57",
    "book": "Philemon",
    "chapters": 1,
    "bytes": 2389
   },
   {
    "part": "58",
    "book": "Hebrews",
    "chapters": 13,
    "bytes": 38369
   },
   {
    "part": "59",
    "book": "James",
    "chapters": 5,
    "bytes": 12380
   },
   {
    "part": "60",
    "book": "1 Peter",
    "chapters": 5,
    "bytes": 13605
   },
   {
    "part": "61",
    "book": "2 Peter",
    "chapters": 3,
    "bytes": 8689
   },
   {
    "part": "62",
    "book": "1 John",
    "chapters": 5,
    "bytes": 12903
   },
   {
    "part": "63",
    "book": "2 John",
    "chapters": 1,
    "bytes": 1659
   },
   {
    "part": "64",
    "book": "3 John",
    "chapters": 1,
    "bytes": 1629
   },
   {
    "part": "65",
    "book": "Jude",
    "chapters": 1,
    "bytes": 3619
   },
   {
    "part": "66",
    "book": "Revelation",
    "chapters": 22,
    "bytes": 60710
   }
  ]
 },
 "quran": {
  "title": "The Qur'an",
  "translation": "Pickthall",
  "license": "Public domain",
  "source": "alquran.cloud",
  "bytes": 853638,
  "parts": [
   {
    "part": "all"
   }
  ],
  "surahs": [
   {
    "n": 1,
    "name": "Al-Faatiha",
    "translation": "The Opening",
    "arabic": "سُورَةُ ٱلْفَاتِحَةِ",
    "revelation": "Meccan",
    "ayahs": 7
   },
   {
    "n": 2,
    "name": "Al-Baqara",
    "translation": "The Cow",
    "arabic": "سُورَةُ البَقَرَةِ",
    "revelation": "Medinan",
    "ayahs": 286
   },
   {
    "n": 3,
    "name": "Aal-i-Imraan",
    "translation": "The Family of Imraan",
    "arabic": "سُورَةُ آلِ عِمۡرَانَ",
    "revelation": "Medinan",
    "ayahs": 200
   },
   {
    "n": 4,
    "name": "An-Nisaa",
    "translation": "The Women",
    "arabic": "سُورَةُ النِّسَاءِ",
    "revelation": "Medinan",
    "ayahs": 176
   },
   {
    "n": 5,
    "name": "Al-Maaida",
    "translation": "The Table",
    "arabic": "سُورَةُ المَائـِدَةِ",
    "revelation": "Medinan",
    "ayahs": 120
   },
   {
    "n": 6,
    "name": "Al-An'aam",
    "translation": "The Cattle",
    "arabic": "سُورَةُ الأَنۡعَامِ",
    "revelation": "Meccan",
    "ayahs": 165
   },
   {
    "n": 7,
    "name": "Al-A'raaf",
    "translation": "The Heights",
    "arabic": "سُورَةُ الأَعۡرَافِ",
    "revelation": "Meccan",
    "ayahs": 206
   },
   {
    "n": 8,
    "name": "Al-Anfaal",
    "translation": "The Spoils of War",
    "arabic": "سُورَةُ الأَنفَالِ",
    "revelation": "Medinan",
    "ayahs": 75
   },
   {
    "n": 9,
    "name": "At-Tawba",
    "translation": "The Repentance",
    "arabic": "سُورَةُ التَّوۡبَةِ",
    "revelation": "Medinan",
    "ayahs": 129
   },
   {
    "n": 10,
    "name": "Yunus",
    "translation": "Jonas",
    "arabic": "سُورَةُ يُونُسَ",
    "revelation": "Meccan",
    "ayahs": 109
   },
   {
    "n": 11,
    "name": "Hud",
    "translation": "Hud",
    "arabic": "سُورَةُ هُودٍ",
    "revelation": "Meccan",
    "ayahs": 123
   },
   {
    "n": 12,
    "name": "Yusuf",
    "translation": "Joseph",
    "arabic": "سُورَةُ يُوسُفَ",
    "revelation": "Meccan",
    "ayahs": 111
   },
   {
    "n": 13,
    "name": "Ar-Ra'd",
    "translation": "The Thunder",
    "arabic": "سُورَةُ الرَّعۡدِ",
    "revelation": "Medinan",
    "ayahs": 43
   },
   {
    "n": 14,
    "name": "Ibrahim",
    "translation": "Abraham",
    "arabic": "سُورَةُ إِبۡرَاهِيمَ",
    "revelation": "Meccan",
    "ayahs": 52
   },
   {
    "n": 15,
    "name": "Al-Hijr",
    "translation": "The Rock",
    "arabic": "سُورَةُ الحِجۡرِ",
    "revelation": "Meccan",
    "ayahs": 99
   },
   {
    "n": 16,
    "name": "An-Nahl",
    "translation": "The Bee",
    "arabic": "سُورَةُ النَّحۡلِ",
    "revelation": "Meccan",
    "ayahs": 128
   },
   {
    "n": 17,
    "name": "Al-Israa",
    "translation": "The Night Journey",
    "arabic": "سُورَةُ الإِسۡرَاءِ",
    "revelation": "Meccan",
    "ayahs": 111
   },
   {
    "n": 18,
    "name": "Al-Kahf",
    "translation": "The Cave",
    "arabic": "سُورَةُ الكَهۡفِ",
    "revelation": "Meccan",
    "ayahs": 110
   },
   {
    "n": 19,
    "name": "Maryam",
    "translation": "Mary",
    "arabic": "سُورَةُ مَرۡيَمَ",
    "revelation": "Meccan",
    "ayahs": 98
   },
   {
    "n": 20,
    "name": "Taa-Haa",
    "translation": "Taa-Haa",
    "arabic": "سُورَةُ طه",
    "revelation": "Meccan",
    "ayahs": 135
   },
   {
    "n": 21,
    "name": "Al-Anbiyaa",
    "translation": "The Prophets",
    "arabic": "سُورَةُ الأَنبِيَاءِ",
    "revelation": "Meccan",
    "ayahs": 112
   },
   {
    "n": 22,
    "name": "Al-Hajj",
    "translation": "The Pilgrimage",
    "arabic": "سُورَةُ الحَجِّ",
    "revelation": "Medinan",
    "ayahs": 78
   },
   {
    "n": 23,
    "name": "Al-Muminoon",
    "translation": "The Believers",
    "arabic": "سُورَةُ المُؤۡمِنُونَ",
    "revelation": "Meccan",
    "ayahs": 118
   },
   {
    "n": 24,
    "name": "An-Noor",
    "translation": "The Light",
    "arabic": "سُورَةُ النُّورِ",
    "revelation": "Medinan",
    "ayahs": 64
   },
   {
    "n": 25,
    "name": "Al-Furqaan",
    "translation": "The Criterion",
    "arabic": "سُورَةُ الفُرۡقَانِ",
    "revelation": "Meccan",
    "ayahs": 77
   },
   {
    "n": 26,
    "name": "Ash-Shu'araa",
    "translation": "The Poets",
    "arabic": "سُورَةُ الشُّعَرَاءِ",
    "revelation": "Meccan",
    "ayahs": 227
   },
   {
    "n": 27,
    "name": "An-Naml",
    "translation": "The Ant",
    "arabic": "سُورَةُ النَّمۡلِ",
    "revelation": "Meccan",
    "ayahs": 93
   },
   {
    "n": 28,
    "name": "Al-Qasas",
    "translation": "The Stories",
    "arabic": "سُورَةُ القَصَصِ",
    "revelation": "Meccan",
    "ayahs": 88
   },
   {
    "n": 29,
    "name": "Al-Ankaboot",
    "translation": "The Spider",
    "arabic": "سُورَةُ العَنكَبُوتِ",
    "revelation": "Meccan",
    "ayahs": 69
   },
   {
    "n": 30,
    "name": "Ar-Room",
    "translation": "The Romans",
    "arabic": "سُورَةُ الرُّومِ",
    "revelation": "Meccan",
    "ayahs": 60
   },
   {
    "n": 31,
    "name": "Luqman",
    "translation": "Luqman",
    "arabic": "سُورَةُ لُقۡمَانَ",
    "revelation": "Meccan",
    "ayahs": 34
   },
   {
    "n": 32,
    "name": "As-Sajda",
    "translation": "The Prostration",
    "arabic": "سُورَةُ السَّجۡدَةِ",
    "revelation": "Meccan",
    "ayahs": 30
   },
   {
    "n": 33,
    "name": "Al-Ahzaab",
    "translation": "The Clans",
    "arabic": "سُورَةُ الأَحۡزَابِ",
    "revelation": "Medinan",
    "ayahs": 73
   },
   {
    "n": 34,
    "name": "Saba",
    "translation": "Sheba",
    "arabic": "سُورَةُ سَبَإٍ",
    "revelation": "Meccan",
    "ayahs": 54
   },
   {
    "n": 35,
    "name": "Faatir",
    "translation": "The Originator",
    "arabic": "سُورَةُ فَاطِرٍ",
    "revelation": "Meccan",
    "ayahs": 45
   },
   {
    "n": 36,
    "name": "Yaseen",
    "translation": "Yaseen",
    "arabic": "سُورَةُ يسٓ",
    "revelation": "Meccan",
    "ayahs": 83
   },
   {
    "n": 37,
    "name": "As-Saaffaat",
    "translation": "Those drawn up in Ranks",
    "arabic": "سُورَةُ الصَّافَّاتِ",
    "revelation": "Meccan",
    "ayahs": 182
   },
   {
    "n": 38,
    "name": "Saad",
    "translation": "The letter Saad",
    "arabic": "سُورَةُ صٓ",
    "revelation": "Meccan",
    "ayahs": 88
   },
   {
    "n": 39,
    "name": "Az-Zumar",
    "translation": "The Groups",
    "arabic": "سُورَةُ الزُّمَرِ",
    "revelation": "Meccan",
    "ayahs": 75
   },
   {
    "n": 40,
    "name": "Ghafir",
    "translation": "The Forgiver",
    "arabic": "سُورَةُ غَافِرٍ",
    "revelation": "Meccan",
    "ayahs": 85
   },
   {
    "n": 41,
    "name": "Fussilat",
    "translation": "Explained in detail",
    "arabic": "سُورَةُ فُصِّلَتۡ",
    "revelation": "Meccan",
    "ayahs": 54
   },
   {
    "n": 42,
    "name": "Ash-Shura",
    "translation": "Consultation",
    "arabic": "سُورَةُ الشُّورَىٰ",
    "revelation": "Meccan",
    "ayahs": 53
   },
   {
    "n": 43,
    "name": "Az-Zukhruf",
    "translation": "Ornaments of gold",
    "arabic": "سُورَةُ الزُّخۡرُفِ",
    "revelation": "Meccan",
    "ayahs": 89
   },
   {
    "n": 44,
    "name": "Ad-Dukhaan",
    "translation": "The Smoke",
    "arabic": "سُورَةُ الدُّخَانِ",
    "revelation": "Meccan",
    "ayahs": 59
   },
   {
    "n": 45,
    "name": "Al-Jaathiya",
    "translation": "Crouching",
    "arabic": "سُورَةُ الجَاثِيَةِ",
    "revelation": "Meccan",
    "ayahs": 37
   },
   {
    "n": 46,
    "name": "Al-Ahqaf",
    "translation": "The Dunes",
    "arabic": "سُورَةُ الأَحۡقَافِ",
    "revelation": "Meccan",
    "ayahs": 35
   },
   {
    "n": 47,
    "name": "Muhammad",
    "translation": "Muhammad",
    "arabic": "سُورَةُ مُحَمَّدٍ",
    "revelation": "Medinan",
    "ayahs": 38
   },
   {
    "n": 48,
    "name": "Al-Fath",
    "translation": "The Victory",
    "arabic": "سُورَةُ الفَتۡحِ",
    "revelation": "Medinan",
    "ayahs": 29
   },
   {
    "n": 49,
    "name": "Al-Hujuraat",
    "translation": "The Inner Apartments",
    "arabic": "سُورَةُ الحُجُرَاتِ",
    "revelation": "Medinan",
    "ayahs": 18
   },
   {
    "n": 50,
    "name": "Qaaf",
    "translation": "The letter Qaaf",
    "arabic": "سُورَةُ قٓ",
    "revelation": "Meccan",
    "ayahs": 45
   },
   {
    "n": 51,
    "name": "Adh-Dhaariyat",
    "translation": "The Winnowing Winds",
    "arabic": "سُورَةُ الذَّارِيَاتِ",
    "revelation": "Meccan",
    "ayahs": 60
   },
   {
    "n": 52,
    "name": "At-Tur",
    "translation": "The Mount",
    "arabic": "سُورَةُ الطُّورِ",
    "revelation": "Meccan",
    "ayahs": 49
   },
   {
    "n": 53,
    "name": "An-Najm",
    "translation": "The Star",
    "arabic": "سُورَةُ النَّجۡمِ",
    "revelation": "Meccan",
    "ayahs": 62
   },
   {
    "n": 54,
    "name": "Al-Qamar",
    "translation": "The Moon",
    "arabic": "سُورَةُ القَمَرِ",
    "revelation": "Meccan",
    "ayahs": 55
   },
   {
    "n": 55,
    "name": "Ar-Rahmaan",
    "translation": "The Beneficent",
    "arabic": "سُورَةُ الرَّحۡمَٰن",
    "revelation": "Medinan",
    "ayahs": 78
   },
   {
    "n": 56,
    "name": "Al-Waaqia",
    "translation": "The Inevitable",
    "arabic": "سُورَةُ الوَاقِعَةِ",
    "revelation": "Meccan",
    "ayahs": 96
   },
   {
    "n": 57,
    "name": "Al-Hadid",
    "translation": "The Iron",
    "arabic": "سُورَةُ الحَدِيدِ",
    "revelation": "Medinan",
    "ayahs": 29
   },
   {
    "n": 58,
    "name": "Al-Mujaadila",
    "translation": "The Pleading Woman",
    "arabic": "سُورَةُ المُجَادلَةِ",
    "revelation": "Medinan",
    "ayahs": 22
   },
   {
    "n": 59,
    "name": "Al-Hashr",
    "translation": "The Exile",
    "arabic": "سُورَةُ الحَشۡرِ",
    "revelation": "Medinan",
    "ayahs": 24
   },
   {
    "n": 60,
    "name": "Al-Mumtahana",
    "translation": "She that is to be examined",
    "arabic": "سُورَةُ المُمۡتَحنَةِ",
    "revelation": "Medinan",
    "ayahs": 13
   },
   {
    "n": 61,
    "name": "As-Saff",
    "translation": "The Ranks",
    "arabic": "سُورَةُ الصَّفِّ",
    "revelation": "Medinan",
    "ayahs": 14
   },
   {
    "n": 62,
    "name": "Al-Jumu'a",
    "translation": "Friday",
    "arabic": "سُورَةُ الجُمُعَةِ",
    "revelation": "Medinan",
    "ayahs": 11
   },
   {
    "n": 63,
    "name": "Al-Munaafiqoon",
    "translation": "The Hypocrites",
    "arabic": "سُورَةُ المُنَافِقُونَ",
    "revelation": "Medinan",
    "ayahs": 11
   },
   {
    "n": 64,
    "name": "At-Taghaabun",
    "translation": "Mutual Disillusion",
    "arabic": "سُورَةُ التَّغَابُنِ",
    "revelation": "Medinan",
    "ayahs": 18
   },
   {
    "n": 65,
    "name": "At-Talaaq",
    "translation": "Divorce",
    "arabic": "سُورَةُ الطَّلَاقِ",
    "revelation": "Medinan",
    "ayahs": 12
   },
   {
    "n": 66,
    "name": "At-Tahrim",
    "translation": "The Prohibition",
    "arabic": "سُورَةُ التَّحۡرِيمِ",
    "revelation": "Medinan",
    "ayahs": 12
   },
   {
    "n": 67,
    "name": "Al-Mulk",
    "translation": "The Sovereignty",
    "arabic": "سُورَةُ المُلۡكِ",
    "revelation": "Meccan",
    "ayahs": 30
   },
   {
    "n": 68,
    "name": "Al-Qalam",
    "translation": "The Pen",
    "arabic": "سُورَةُ القَلَمِ",
    "revelation": "Meccan",
    "ayahs": 52
   },
   {
    "n": 69,
    "name": "Al-Haaqqa",
    "translation": "The Reality",
    "arabic": "سُورَةُ الحَاقَّةِ",
    "revelation": "Meccan",
    "ayahs": 52
   },
   {
    "n": 70,
    "name": "Al-Ma'aarij",
    "translation": "The Ascending Stairways",
    "arabic": "سُورَةُ المَعَارِجِ",
    "revelation": "Meccan",
    "ayahs": 44
   },
   {
    "n": 71,
    "name": "Nooh",
    "translation": "Noah",
    "arabic": "سُورَةُ نُوحٍ",
    "revelation": "Meccan",
    "ayahs": 28
   },
   {
    "n": 72,
    "name": "Al-Jinn",
    "translation": "The Jinn",
    "arabic": "سُورَةُ الجِنِّ",
    "revelation": "Meccan",
    "ayahs": 28
   },
   {
    "n": 73,
    "name": "Al-Muzzammil",
    "translation": "The Enshrouded One",
    "arabic": "سُورَةُ المُزَّمِّلِ",
    "revelation": "Meccan",
    "ayahs": 20
   },
   {
    "n": 74,
    "name": "Al-Muddaththir",
    "translation": "The Cloaked One",
    "arabic": "سُورَةُ المُدَّثِّرِ",
    "revelation": "Meccan",
    "ayahs": 56
   },
   {
    "n": 75,
    "name": "Al-Qiyaama",
    "translation": "The Resurrection",
    "arabic": "سُورَةُ القِيَامَةِ",
    "revelation": "Meccan",
    "ayahs": 40
   },
   {
    "n": 76,
    "name": "Al-Insaan",
    "translation": "Man",
    "arabic": "سُورَةُ الإِنسَانِ",
    "revelation": "Medinan",
    "ayahs": 31
   },
   {
    "n": 77,
    "name": "Al-Mursalaat",
    "translation": "The Emissaries",
    "arabic": "سُورَةُ المُرۡسَلَاتِ",
    "revelation": "Meccan",
    "ayahs": 50
   },
   {
    "n": 78,
    "name": "An-Naba",
    "translation": "The Announcement",
    "arabic": "سُورَةُ النَّبَإِ",
    "revelation": "Meccan",
    "ayahs": 40
   },
   {
    "n": 79,
    "name": "An-Naazi'aat",
    "translation": "Those who drag forth",
    "arabic": "سُورَةُ النَّازِعَاتِ",
    "revelation": "Meccan",
    "ayahs": 46
   },
   {
    "n": 80,
    "name": "Abasa",
    "translation": "He frowned",
    "arabic": "سُورَةُ عَبَسَ",
    "revelation": "Meccan",
    "ayahs": 42
   },
   {
    "n": 81,
    "name": "At-Takwir",
    "translation": "The Overthrowing",
    "arabic": "سُورَةُ التَّكۡوِيرِ",
    "revelation": "Meccan",
    "ayahs": 29
   },
   {
    "n": 82,
    "name": "Al-Infitaar",
    "translation": "The Cleaving",
    "arabic": "سُورَةُ الانفِطَارِ",
    "revelation": "Meccan",
    "ayahs": 19
   },
   {
    "n": 83,
    "name": "Al-Mutaffifin",
    "translation": "Defrauding",
    "arabic": "سُورَةُ المُطَفِّفِينَ",
    "revelation": "Meccan",
    "ayahs": 36
   },
   {
    "n": 84,
    "name": "Al-Inshiqaaq",
    "translation": "The Splitting Open",
    "arabic": "سُورَةُ الانشِقَاقِ",
    "revelation": "Meccan",
    "ayahs": 25
   },
   {
    "n": 85,
    "name": "Al-Burooj",
    "translation": "The Constellations",
    "arabic": "سُورَةُ البُرُوجِ",
    "revelation": "Meccan",
    "ayahs": 22
   },
   {
    "n": 86,
    "name": "At-Taariq",
    "translation": "The Morning Star",
    "arabic": "سُورَةُ الطَّارِقِ",
    "revelation": "Meccan",
    "ayahs": 17
   },
   {
    "n": 87,
    "name": "Al-A'laa",
    "translation": "The Most High",
    "arabic": "سُورَةُ الأَعۡلَىٰ",
    "revelation": "Meccan",
    "ayahs": 19
   },
   {
    "n": 88,
    "name": "Al-Ghaashiya",
    "translation": "The Overwhelming",
    "arabic": "سُورَةُ الغَاشِيَةِ",
    "revelation": "Meccan",
    "ayahs": 26
   },
   {
    "n": 89,
    "name": "Al-Fajr",
    "translation": "The Dawn",
    "arabic": "سُورَةُ الفَجۡرِ",
    "revelation": "Meccan",
    "ayahs": 30
   },
   {
    "n": 90,
    "name": "Al-Balad",
    "translation": "The City",
    "arabic": "سُورَةُ البَلَدِ",
    "revelation": "Meccan",
    "ayahs": 20
   },
   {
    "n": 91,
    "name": "Ash-Shams",
    "translation": "The Sun",
    "arabic": "سُورَةُ الشَّمۡسِ",
    "revelation": "Meccan",
    "ayahs": 15
   },
   {
    "n": 92,
    "name": "Al-Lail",
    "translation": "The Night",
    "arabic": "سُورَةُ اللَّيۡلِ",
    "revelation": "Meccan",
    "ayahs": 21
   },
   {
    "n": 93,
    "name": "Ad-Dhuhaa",
    "translation": "The Morning Hours",
    "arabic": "سُورَةُ الضُّحَىٰ",
    "revelation": "Meccan",
    "ayahs": 11
   },
   {
    "n": 94,
    "name": "Ash-Sharh",
    "translation": "The Consolation",
    "arabic": "سُورَةُ الشَّرۡحِ",
    "revelation": "Meccan",
    "ayahs": 8
   },
   {
    "n": 95,
    "name": "At-Tin",
    "translation": "The Fig",
    "arabic": "سُورَةُ التِّينِ",
    "revelation": "Meccan",
    "ayahs": 8
   },
   {
    "n": 96,
    "name": "Al-Alaq",
    "translation": "The Clot",
    "arabic": "سُورَةُ العَلَقِ",
    "revelation": "Meccan",
    "ayahs": 19
   },
   {
    "n": 97,
    "name": "Al-Qadr",
    "translation": "The Power, Fate",
    "arabic": "سُورَةُ القَدۡرِ",
    "revelation": "Meccan",
    "ayahs": 5
   },
   {
    "n": 98,
    "name": "Al-Bayyina",
    "translation": "The Evidence",
    "arabic": "سُورَةُ البَيِّنَةِ",
    "revelation": "Medinan",
    "ayahs": 8
   },
   {
    "n": 99,
    "name": "Az-Zalzala",
    "translation": "The Earthquake",
    "arabic": "سُورَةُ الزَّلۡزَلَةِ",
    "revelation": "Medinan",
    "ayahs": 8
   },
   {
    "n": 100,
    "name": "Al-Aadiyaat",
    "translation": "The Chargers",
    "arabic": "سُورَةُ العَادِيَاتِ",
    "revelation": "Meccan",
    "ayahs": 11
   },
   {
    "n": 101,
    "name": "Al-Qaari'a",
    "translation": "The Calamity",
    "arabic": "سُورَةُ القَارِعَةِ",
    "revelation": "Meccan",
    "ayahs": 11
   },
   {
    "n": 102,
    "name": "At-Takaathur",
    "translation": "Competition",
    "arabic": "سُورَةُ التَّكَاثُرِ",
    "revelation": "Meccan",
    "ayahs": 8
   },
   {
    "n": 103,
    "name": "Al-Asr",
    "translation": "The Declining Day, Epoch",
    "arabic": "سُورَةُ العَصۡرِ",
    "revelation": "Meccan",
    "ayahs": 3
   },
   {
    "n": 104,
    "name": "Al-Humaza",
    "translation": "The Traducer",
    "arabic": "سُورَةُ الهُمَزَةِ",
    "revelation": "Meccan",
    "ayahs": 9
   },
   {
    "n": 105,
    "name": "Al-Fil",
    "translation": "The Elephant",
    "arabic": "سُورَةُ الفِيلِ",
    "revelation": "Meccan",
    "ayahs": 5
   },
   {
    "n": 106,
    "name": "Quraish",
    "translation": "Quraysh",
    "arabic": "سُورَةُ قُرَيۡشٍ",
    "revelation": "Meccan",
    "ayahs": 4
   },
   {
    "n": 107,
    "name": "Al-Maa'un",
    "translation": "Almsgiving",
    "arabic": "سُورَةُ المَاعُونِ",
    "revelation": "Meccan",
    "ayahs": 7
   },
   {
    "n": 108,
    "name": "Al-Kawthar",
    "translation": "Abundance",
    "arabic": "سُورَةُ الكَوۡثَرِ",
    "revelation": "Meccan",
    "ayahs": 3
   },
   {
    "n": 109,
    "name": "Al-Kaafiroon",
    "translation": "The Disbelievers",
    "arabic": "سُورَةُ الكَافِرُونَ",
    "revelation": "Meccan",
    "ayahs": 6
   },
   {
    "n": 110,
    "name": "An-Nasr",
    "translation": "Divine Support",
    "arabic": "سُورَةُ النَّصۡرِ",
    "revelation": "Medinan",
    "ayahs": 3
   },
   {
    "n": 111,
    "name": "Al-Masad",
    "translation": "The Palm Fibre",
    "arabic": "سُورَةُ المَسَدِ",
    "revelation": "Meccan",
    "ayahs": 5
   },
   {
    "n": 112,
    "name": "Al-Ikhlaas",
    "translation": "Sincerity",
    "arabic": "سُورَةُ الإِخۡلَاصِ",
    "revelation": "Meccan",
    "ayahs": 4
   },
   {
    "n": 113,
    "name": "Al-Falaq",
    "translation": "The Dawn",
    "arabic": "سُورَةُ الفَلَقِ",
    "revelation": "Meccan",
    "ayahs": 5
   },
   {
    "n": 114,
    "name": "An-Naas",
    "translation": "Mankind",
    "arabic": "سُورَةُ النَّاسِ",
    "revelation": "Meccan",
    "ayahs": 6
   }
  ]
 }
};
