/* First Light: the body chapter
   Extracted verbatim from first_light_year_4.html.
   Declares globals; loaded by a classic <script> tag. */

const BODY_TEACH=[
["The standing trade","Eight to twelve hours upright is a physiological event, and the trade treats it as furniture. Blood pools in the veins of the feet and calves when the calf muscle stops pumping, which is why the end of a shift aches in a way a hike never does: a hike pumps, a station holds. The plantar fascia, loaded since doors, tightens overnight and announces itself on the first step of the morning. None of this is weakness; it is hydraulics. The counters are mechanical too: calf raises at the rail when the room is quiet, the sole rolled over a bottle after close, and legs up the wall, which is not a yoga flourish but a drain. And the one rule that saves careers: kegs, cases, and ice buckets are lifted with the hips hinged and the load close, because the low back is a bad crane and a worse martyr."],
["Sleep after the late shift","The trade\u2019s sleep problem is not discipline; it is architecture. A closer\u2019s night ends when the sun is thinking about rising, and the body\u2019s clock reads that light as a command to wake. So the craft is light management. Guard one anchor window that never moves: the same four hours, say four to eight, defended on workdays and days off alike, with everything else negotiable around it. Treat the commute home as dusk: sunglasses against the morning light, because the clock in the eye does not know you are going to bed. Make the room actually dark, put the phone to bed somewhere that is not the bed, and stop the caffeine six to eight hours before you intend to sleep; the half-life is real even when the tiredness argues otherwise. Seneca ran his nightly audit only after the lamp was carried out and the room went dark. He would have understood a life lived against the sun. He would also have defended the anchor window like a border."],
["The nightcap","Here is the physiology, plainly, from an app that also teaches people to build drinks and respects the craft. Alcohol shortens the walk to sleep; that part is true, and it is why the shift drink works. Then it collects: the second half of the night fragments, REM is suppressed, and the recovery the body was owed is quietly repossessed. The nightcap borrows from tomorrow at interest. This is not temperance copy; it is arithmetic, and the trade deserves the honest ledger. The practices in this book already hold the alternative. Voluntary Discomfort was built for exactly this trade: skip the shift drink once this week, on purpose, and watch what the morning gives back. If skipping it once feels larger than it should, that is information too, worth exactly one honest line in the examen, and there is a longer word on this in the small hours of the app when you want it."],
["Water and the small hours","Kitchens run hot and bars run fast, and both sweat more than anyone credits. The complaint that arrives at hour eight as exhaustion, a headache, or a temper with a short fuse is often just fluid; the body\u2019s gauges are coarse, and thirst reports late. The craft answer is the same as every other station discipline: mise en place. A litre bottle filled at line-up, finished by the push, filled again; a glass of water with whatever is eaten before doors; one more before bed after a close, because tomorrow\u2019s first hour is poured tonight. The Stoics would call this the body\u2019s portion of prosoch\u0113 (attention), and they would be right: nobody good at this trade runs their station out of ice, and the body is the first station."],

["The body is not the obstacle","Every ascetic tradition was tempted to treat the body as an enemy, and the deepest teachers of each one refused. The Buddha abandoned six years of starvation for the middle way, having learned that a body too weak to sit is no use to a mind trying to see. Yoga makes the point structurally: the postures exist to make sitting possible. Musonius Rufus, who taught the lame Epictetus, insisted the body be trained alongside the soul: not worshipped, but kept fit for its work, because the body is the instrument the work is done with."],
["Steady and comfortable","Patañjali defines a posture in three Sanskrit words: <em>sthira sukham āsanam</em>, steady and at ease. That is the entire instruction, and it is a corrective to nearly everything modern exercise culture assumes. Not maximal, not impressive, not painful. A posture is correct when you can hold it with stability and without strain, which means the standard is set by your body today, not by the person beside you or the one you were last year."],
["Breath is the bridge","Prāṇāyāma sits at the center of the eight limbs because breath is the one system that is both automatic and voluntary: the hinge between what the body does to you and what you do with it. Slow the breath and the nervous system follows; this is the oldest known technology for governing one's own state. The Stoic pause before responding, the Zen count of ten, the Sufi <em>dhikr</em>, all of them work the same lever."],
["Strength is a form of service","Socrates told a young Athenian it was shameful to grow old without ever seeing what his body was capable of, not out of vanity, but because a citizen owed the city a body that could carry its share. The Stoics inherited this: the point of physical training is capability for duty, not display. What you build in the body is spent on other people: the friend helped to move, the child carried, the decades of usefulness you keep in reserve."],
["Discipline of the small hour","Nothing here works by intensity. It works by return. The Confucian daily self-examination, the monastic bell, the Stoic morning: all assume a modest practice repeated past the point where motivation is involved. Twenty honest minutes performed four hundred times will remake a body; two brutal hours performed twice will not. The tradition's word for this is not <em>willpower</em>. It is <em>habit</em>."],
["Rest is part of the practice","The Sabbath is the first thing the Hebrew Bible calls holy, and it is a law about stopping. Aesop, caught at play and mocked for it, pointed to an unstrung bow: kept always bent, it breaks. Recovery is not the absence of training but a phase of it: the interval in which the work you did actually becomes the body you have. A practice with no rest in it is not a discipline; it is an anxiety with good posture."]];

const EIGHT_LIMBS=[
["Yama","Restraint toward others: non-harming, truthfulness, non-stealing, moderation, non-grasping."],
["Niyama","Restraint toward oneself: cleanliness, contentment, disciplined effort, self-study, surrender."],
["Āsana","Posture. Steady and comfortable; the seat the rest of the practice is built on."],
["Prāṇāyāma","Regulation of the breath, and through it, of energy and attention."],
["Pratyāhāra","Withdrawal of the senses: the deliberate turning down of external input."],
["Dhāraṇā","Concentration: holding attention on a single point without wandering."],
["Dhyāna","Meditation: the point held so steadily that the effort of holding falls away."],
["Samādhi","Absorption: the observer and the observed no longer standing apart."]];

const BODY_VIDEOS=[
{id:"y87vSUoIMGU",frame:"Unwinding",note:"A full-body stretch to close a working day, or to stand alone on a rest day."},
{id:"Z5DX8MYcl00",frame:"The Practice",note:"Return to this one often enough that it stops feeling like a decision."},
{id:"ZSSC9X_6wo4",start:119,frame:"The Session",note:"Begins a couple of minutes in, where the practice itself starts."},
{id:"OJAo8QVkRq0",frame:"The Work",note:"For the days when capability, not calm, is what you are building."},
{id:"ka9xQQ9o7H4",frame:"The Steady Hour",note:"Moderate, repeatable, and meant to be come back to."},
{id:"eAi7EAE6-cU",start:1054,frame:"The Long Form",note:"Opens partway in, at the section worth returning to."}];
