/* First Light: the lift.

   A bank of uplifting lines for the morning page, beside the dated voice: film
   lines, and voices from people who made or endured something. Same citation
   policy as the year: a confident false citation is worse than an honest
   "attributed to". Film lines carry the character who says them, the film and
   its year, and are kept short and verbatim. Where a famous line's origin is
   disputed the source says so, and lines whose real author is a different
   person from the famous name are credited to the person who wrote them.

   Entries are [line, source, kind], kind 'film' or 'voice'. Two are drawn each
   day by the day of the year; "Another" deals a fresh pair for the session and
   records nothing. Declares globals; loaded by a classic <script> tag. */

const UPLIFT = [
  /* ---- films ---- */
  ["Get busy living, or get busy dying.", "Andy Dufresne, The Shawshank Redemption (1994)", "film"],
  ["Hope is a good thing, maybe the best of things, and no good thing ever dies.", "Andy Dufresne, The Shawshank Redemption (1994)", "film"],
  ["It ain't about how hard you hit. It's about how hard you can get hit and keep moving forward.", "Rocky Balboa, Rocky Balboa (2006)", "film"],
  ["All I wanna do is go the distance.", "Rocky Balboa, Rocky (1976)", "film"],
  ["Going in one more round when you don't think you can. That's what makes all the difference in your life.", "Rocky Balboa, Rocky IV (1985)", "film"],
  ["If I can change, and you can change, everybody can change.", "Rocky Balboa, Rocky IV (1985)", "film"],
  ["One step at a time. One punch at a time. One round at a time.", "Rocky Balboa, Creed (2015)", "film"],
  ["Do, or do not. There is no try.", "Yoda, The Empire Strikes Back (1980)", "film"],
  ["Never tell me the odds.", "Han Solo, The Empire Strikes Back (1980)", "film"],
  ["The greatest teacher, failure is.", "Yoda, The Last Jedi (2017)", "film"],
  ["Hope is like the sun. If you only believe in it when you can see it, you'll never make it through the night.", "Amilyn Holdo, quoting Leia Organa, The Last Jedi (2017)", "film"],
  ["Rebellions are built on hope.", "Jyn Erso, Rogue One (2016)", "film"],
  ["Carpe diem. Seize the day, boys. Make your lives extraordinary.", "John Keating, Dead Poets Society (1989)", "film"],
  ["No matter what anybody tells you, words and ideas can change the world.", "John Keating, Dead Poets Society (1989)", "film"],
  ["You is kind. You is smart. You is important.", "Aibileen Clark, The Help (2011)", "film"],
  ["Just keep swimming.", "Dory, Finding Nemo (2003)", "film"],
  ["The flower that blooms in adversity is the most rare and beautiful of all.", "The Emperor, Mulan (1998)", "film"],
  ["Oh yes, the past can hurt. But the way I see it, you can either run from it or learn from it.", "Rafiki, The Lion King (1994)", "film"],
  ["Remember who you are.", "Mufasa, The Lion King (1994)", "film"],
  ["Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.", "Ferris Bueller, Ferris Bueller's Day Off (1986)", "film"],
  ["Every man dies. Not every man really lives.", "William Wallace, Braveheart (1995)", "film"],
  ["It's not who I am underneath, but what I do that defines me.", "Bruce Wayne, Batman Begins (2005)", "film"],
  ["Why do we fall, sir? So that we can learn to pick ourselves up.", "Alfred Pennyworth, Batman Begins (2005)", "film"],
  ["Don't ever let somebody tell you you can't do something. Not even me. You got a dream, you gotta protect it.", "Chris Gardner, The Pursuit of Happyness (2006)", "film"],
  ["You want something, go get it. Period.", "Chris Gardner, The Pursuit of Happyness (2006)", "film"],
  ["All we have to decide is what to do with the time that is given us.", "Gandalf, The Fellowship of the Ring (2001)", "film"],
  ["Even the smallest person can change the course of the future.", "Galadriel, The Fellowship of the Ring (2001)", "film"],
  ["There's some good in this world, Mr. Frodo, and it's worth fighting for.", "Samwise Gamgee, The Two Towers (2002)", "film"],
  ["You're braver than you believe, and stronger than you seem, and smarter than you think.", "Christopher Robin, Pooh's Grand Adventure (1997); the line is the film's, not A. A. Milne's", "film"],
  ["To infinity and beyond!", "Buzz Lightyear, Toy Story (1995)", "film"],
  ["Adventure is out there!", "Ellie, Up (2009)", "film"],
  ["Thanks for the adventure. Now go have a new one.", "Ellie's note to Carl, Up (2009)", "film"],
  ["Sometimes the right path is not the easiest one.", "Grandmother Willow, Pocahontas (1995)", "film"],
  ["The very things that hold you down are going to lift you up.", "Timothy Q. Mouse, Dumbo (1941)", "film"],
  ["Keep moving forward.", "The Robinson family motto, Meet the Robinsons (2007)", "film"],
  ["Anyone can cook.", "Auguste Gusteau, Ratatouille (2007)", "film"],
  ["Not everyone can become a great artist, but a great artist can come from anywhere.", "Anton Ego, Ratatouille (2007)", "film"],
  ["Our lives are defined by opportunities, even the ones we miss.", "Benjamin Button, The Curious Case of Benjamin Button (2008)", "film"],
  ["It's never too late or, in my case, too early to be whoever you want to be. There's no time limit, stop whenever you want.", "Benjamin's letter, The Curious Case of Benjamin Button (2008)", "film"],
  ["After all, tomorrow is another day!", "Scarlett O'Hara, Gone with the Wind (1939)", "film"],
  ["A heart is not judged by how much you love, but by how much you are loved by others.", "The Wizard, The Wizard of Oz (1939)", "film"],
  ["There's no place like home.", "Dorothy Gale, The Wizard of Oz (1939)", "film"],
  ["Life was like a box of chocolates. You never know what you're gonna get.", "Forrest Gump, quoting his mother, Forrest Gump (1994)", "film"],
  ["You got to put the past behind you before you can move on.", "Forrest Gump, quoting his mother, Forrest Gump (1994)", "film"],
  ["Some people can't believe in themselves until someone else believes in them first.", "Sean Maguire, Good Will Hunting (1997)", "film"],
  ["Sometimes it is the people no one imagines anything of who do the things that no one can imagine.", "Joan Clarke, The Imitation Game (2014)", "film"],
  ["You mustn't be afraid to dream a little bigger, darling.", "Eames, Inception (2010)", "film"],
  ["Happiness can be found even in the darkest of times, if one only remembers to turn on the light.", "Albus Dumbledore, Harry Potter and the Prisoner of Azkaban (2004)", "film"],
  ["It is our choices, Harry, that show what we truly are, far more than our abilities.", "Albus Dumbledore, Harry Potter and the Chamber of Secrets (2002)", "film"],
  ["It does not do to dwell on dreams and forget to live.", "Albus Dumbledore, Harry Potter and the Philosopher's Stone (2001)", "film"],
  ["With great power comes great responsibility.", "Uncle Ben, Spider-Man (2002)", "film"],
  ["Make each day count.", "Jack Dawson, Titanic (1997)", "film"],
  ["Ohana means family. Family means nobody gets left behind or forgotten.", "Lilo, Lilo and Stitch (2002)", "film"],
  ["The past is just a story we tell ourselves.", "Samantha, Her (2013)", "film"],
  ["Don't let anyone ever make you feel like you don't deserve what you want.", "Patrick Verona, 10 Things I Hate About You (1999)", "film"],
  ["It's what you do right now that makes a difference.", "Jeff Struecker, Black Hawk Down (2001)", "film"],
  ["What we do in life echoes in eternity.", "Maximus, Gladiator (2000)", "film"],
  ["Even miracles take a little time.", "The Fairy Godmother, Cinderella (1950)", "film"],
  ["Have courage and be kind.", "Ella's mother, Cinderella (2015)", "film"],
  ["This is perhaps the greatest risk that any of us will take: to be seen as we truly are.", "Cinderella (2015)", "film"],
  ["Second star to the right and straight on till morning.", "Peter Pan, Peter Pan (1953)", "film"],
  ["All it takes is faith and trust.", "Peter Pan, Peter Pan (1953)", "film"],
  ["Just because someone stumbles and loses their way, doesn't mean they're lost forever.", "Charles Xavier, X-Men: Days of Future Past (2014)", "film"],
  ["Not all treasure is silver and gold, mate.", "Jack Sparrow, Pirates of the Caribbean: The Curse of the Black Pearl (2003)", "film"],
  ["Don't think. Feel.", "Lee, Enter the Dragon (1973)", "film"],
  ["Yesterday is history, tomorrow is a mystery, but today is a gift. That is why it is called the present.", "Oogway, Kung Fu Panda (2008)", "film"],
  ["There is no secret ingredient. It's just you.", "Mr. Ping, Kung Fu Panda (2008)", "film"],
  ["Your story may not have such a happy beginning, but that doesn't make you who you are. It is the rest of your story, who you choose to be.", "The Soothsayer, Kung Fu Panda 2 (2011)", "film"],
  ["Every passing minute is another chance to turn it all around.", "Sofia Serrano, Vanilla Sky (2001)", "film"],
  ["Some people are worth melting for.", "Olaf, Frozen (2013)", "film"],
  ["Life's not a spectator sport. If watching is all you're gonna do, then you're gonna watch your life go by without you.", "Laverne, The Hunchback of Notre Dame (1996)", "film"],
  ["No man is a failure who has friends.", "Clarence's inscription, It's a Wonderful Life (1946)", "film"],
  ["Each man's life touches so many other lives. When he isn't around he leaves an awful hole, doesn't he?", "Clarence, It's a Wonderful Life (1946)", "film"],
  ["No matter what happens tomorrow, or for the rest of my life, I'm happy now.", "Phil Connors, Groundhog Day (1993)", "film"],
  ["I just try to live every day as if I've deliberately come back to this one day, to enjoy it, as if it was the full final day of my extraordinary, ordinary life.", "Tim Lake, About Time (2013)", "film"],
  ["In this lifetime, you don't have to prove nothin' to nobody except yourself.", "Fortune, Rudy (1993)", "film"],
  ["I don't care what the scoreboard says at the end of the game, in my book we're gonna be winners.", "Coach Norman Dale, Hoosiers (1986)", "film"],
  ["Attitude reflects leadership, captain.", "Julius Campbell, Remember the Titans (2000)", "film"],
  ["Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure.", "Marianne Williamson, A Return to Love (1992), recited by Timo Cruz in Coach Carter (2005)", "film"],
  ["It's ok to lose to opponent. It's never okay to lose to fear.", "Mr. Miyagi, The Karate Kid Part III (1989)", "film"],
  ["A gold medal is a wonderful thing. But if you're not enough without it, you'll never be enough with it.", "Irv Blitzer, Cool Runnings (1993)", "film"],
  ["It's supposed to be hard. If it wasn't hard, everyone would do it. The hard is what makes it great.", "Jimmy Dugan, A League of Their Own (1992)", "film"],
  ["If you build it, he will come.", "The voice in the corn, Field of Dreams (1989)", "film"],
  ["Great moments are born from great opportunity.", "Herb Brooks, Miracle (2004)", "film"],
  ["We've always defined ourselves by the ability to overcome the impossible.", "Cooper, Interstellar (2014)", "film"],
  ["You solve one problem and you solve the next one, and then the next. And if you solve enough problems, you get to come home.", "Mark Watney, The Martian (2015)", "film"],
  ["Failure is not an option.", "Gene Kranz, Apollo 13 (1995)", "film"],
  ["I'm going to live every minute of it.", "Joe Gardner, Soul (2020)", "film"],
  ["In Zootopia, anyone can be anything.", "Judy Hopps, Zootopia (2016)", "film"],
  ["To see the world, things dangerous to come to, to see behind walls, draw closer, to find each other, and to feel. That is the purpose of life.", "The magazine's motto, The Secret Life of Walter Mitty (2013)", "film"],
  ["Find the joy in your life.", "Carter Chambers, The Bucket List (2007)", "film"],
  ["I know what I have to do now. I gotta keep breathing. Because tomorrow the sun will rise. Who knows what the tide could bring?", "Chuck Noland, Cast Away (2000)", "film"],
  ["You don't throw a whole life away just 'cause he's banged up a little.", "Tom Smith, Seabiscuit (2003)", "film"],
  ["When given the choice between being right or being kind, choose kind.", "Mr. Browne's precept, Wonder (2017), after Wayne Dyer", "film"],
  ["If we're kind and polite the world will be right.", "Paddington, quoting Aunt Lucy, Paddington 2 (2017)", "film"],
  ["If you put your mind to it, you can accomplish anything.", "Marty McFly, Back to the Future (1985)", "film"],
  ["There's a difference between knowing the path and walking the path.", "Morpheus, The Matrix (1999)", "film"],
  ["I must not fear. Fear is the mind-killer.", "Paul Atreides, Dune (2021), after Frank Herbert", "film"],
  ["I never saved anything for the swim back.", "Vincent Freeman, Gattaca (1997)", "film"],
  ["Good morning, and in case I don't see ya, good afternoon, good evening, and good night!", "Truman Burbank, The Truman Show (1998)", "film"],
  ["That'll do, pig. That'll do.", "Farmer Hoggett, Babe (1995)", "film"],
  ["Fear is not real. It is a product of thoughts you create. Danger is very real, but fear is a choice.", "Cypher Raige, After Earth (2013)", "film"],

  /* ---- voices ---- */
  ["Be water, my friend.", "Bruce Lee, interview with Pierre Berton (1971)", "voice"],
  ["A man of genius makes no mistakes. His errors are volitional and are the portals of discovery.", "James Joyce, Ulysses (1922)", "voice"],
  ["Fall seven times, stand up eight.", "Japanese proverb", "voice"],
  ["The best way out is always through.", "Robert Frost, A Servant to Servants (1914)", "voice"],
  ["Two roads diverged in a wood, and I, I took the one less traveled by, and that has made all the difference.", "Robert Frost, The Road Not Taken (1916)", "voice"],
  ["Whether you think you can, or you think you can't, you're right.", "Attributed to Henry Ford", "voice"],
  ["It always seems impossible until it's done.", "Attributed to Nelson Mandela", "voice"],
  ["Courage is resistance to fear, mastery of fear, not absence of fear.", "Mark Twain, Pudd'nhead Wilson (1894)", "voice"],
  ["Not all those who wander are lost.", "J. R. R. Tolkien, The Fellowship of the Ring (1954)", "voice"],
  ["Hope is the thing with feathers that perches in the soul.", "Emily Dickinson", "voice"],
  ["We are all in the gutter, but some of us are looking at the stars.", "Oscar Wilde, Lady Windermere's Fan (1892)", "voice"],
  ["It is never too late to be what you might have been.", "Attributed to George Eliot; not found in her writings", "voice"],
  ["You must do the thing you think you cannot do.", "Eleanor Roosevelt, You Learn by Living (1960)", "voice"],
  ["Do what you can, with what you have, where you are.", "Theodore Roosevelt, An Autobiography (1913), crediting Squire Bill Widener", "voice"],
  ["Nothing in life is to be feared, it is only to be understood.", "Attributed to Marie Curie", "voice"],
  ["I have not failed. I've just found ten thousand ways that won't work.", "Attributed to Thomas Edison", "voice"],
  ["You miss one hundred percent of the shots you don't take.", "Attributed to Wayne Gretzky; he told it several ways", "voice"],
  ["It's not whether you get knocked down, it's whether you get up.", "Attributed to Vince Lombardi", "voice"],
  ["Start where you are. Use what you have. Do what you can.", "Attributed to Arthur Ashe", "voice"],
  ["Amateurs sit and wait for inspiration, the rest of us just get up and go to work.", "Stephen King, On Writing (2000)", "voice"],
  ["You can't use up creativity. The more you use, the more you have.", "Maya Angelou, Bell Telephone Magazine interview (1982)", "voice"],
  ["Still I rise.", "Maya Angelou, And Still I Rise (1978)", "voice"],
  ["Chop wood, carry water.", "Zen saying", "voice"],
  ["This too shall pass.", "Persian adage, retold by Abraham Lincoln (1859)", "voice"],
  ["A ship in harbor is safe, but that is not what ships are built for.", "John A. Shedd, Salt from My Attic (1928)", "voice"],
  ["The wound is the place where the Light enters you.", "Rumi, as rendered by Coleman Barks", "voice"],
  ["Be kind, for everyone you meet is fighting a hard battle.", "Ian Maclaren (John Watson), 1897", "voice"],
  ["No act of kindness, no matter how small, is ever wasted.", "Aesop, The Lion and the Mouse", "voice"],
  ["We rise by lifting others.", "Attributed to Robert G. Ingersoll; not found in his writings", "voice"],
  ["The world breaks every one and afterward many are strong at the broken places.", "Ernest Hemingway, A Farewell to Arms (1929)", "voice"],
  ["The only way to do great work is to love what you do.", "Steve Jobs, Stanford commencement address (2005)", "voice"],
  ["Stay hungry. Stay foolish.", "Whole Earth Catalog (1974), as quoted by Steve Jobs", "voice"],
  ["Let everything happen to you: beauty and terror. Just keep going. No feeling is final.", "Rainer Maria Rilke, Book of Hours, translated by Barrows and Macy", "voice"],
  ["The only limit to our realization of tomorrow will be our doubts of today.", "Franklin D. Roosevelt, undelivered address (1945)", "voice"],
  ["Act as if what you do makes a difference. It does.", "Attributed to William James", "voice"],
  ["Hold fast to dreams, for if dreams die, life is a broken-winged bird that cannot fly.", "Langston Hughes, Dreams (1922)", "voice"],
  ["I am the master of my fate, I am the captain of my soul.", "William Ernest Henley, Invictus (1888)", "voice"],
  ["Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.", "W. H. Murray (1951), often misattributed to Goethe", "voice"],
  ["How wonderful it is that nobody need wait a single moment before starting to improve the world.", "Anne Frank, diary (1944)", "voice"],
  ["The brick walls are there for a reason. They give us a chance to show how badly we want something.", "Randy Pausch, The Last Lecture (2007)", "voice"],
  ["Do not let what you cannot do interfere with what you can do.", "Attributed to John Wooden", "voice"],
  ["Things work out best for those who make the best of how things work out.", "Attributed to John Wooden", "voice"],
  ["Optimism is the faith that leads to achievement.", "Helen Keller, Optimism (1903)", "voice"],
  ["Although the world is full of suffering, it is also full of the overcoming of it.", "Helen Keller, Optimism (1903)", "voice"],
  ["Life is either a daring adventure or nothing at all.", "Helen Keller, The Open Door (1957)", "voice"],
  ["If one advances confidently in the direction of his dreams, he will meet with a success unexpected in common hours.", "Henry David Thoreau, Walden (1854)", "voice"],
  ["You're off to great places! Today is your day! Your mountain is waiting, so get on your way!", "Dr. Seuss, Oh, the Places You'll Go! (1990)", "voice"],
  ["Unless someone like you cares a whole awful lot, nothing is going to get better. It's not.", "Dr. Seuss, The Lorax (1971)", "voice"],
  ["Hospitality is present when something happens for you. It is absent when something happens to you.", "Danny Meyer, Setting the Table (2006)", "voice"],
  ["Your body is not a temple, it's an amusement park. Enjoy the ride.", "Anthony Bourdain, Kitchen Confidential (2000)", "voice"],
  ["Perseverance is not a long race; it is many short races one after the other.", "Attributed to Walter Elliot", "voice"],
  ["Alone we can do so little; together we can do so much.", "Attributed to Helen Keller", "voice"],
  ["Turn your wounds into wisdom.", "Attributed to Oprah Winfrey", "voice"],
  ["If you want to go fast, go alone. If you want to go far, go together.", "Proverb, origin uncertain", "voice"]
];

/* Three short teachings per month, in the app's own voice, keyed to the twelve
   themes of the year. One is shown each morning by the day of the year. */
const TEACHINGS = [
  /* January: Beginning Again */
  ["Every morning is a clean sheet. Nothing you did yesterday is written on it, and nothing you failed to do. The only mark on it is the one you make first, so make it small and make it now.",
   "A beginning does not need a plan, a mood or a sign. It needs one honest action taken before the day has a chance to argue. The kettle, the walk, the first line. Begin, and let the rest of the day catch up.",
   "You are allowed to start again as many times as you need to. Starting over is not evidence of failure; it is the whole method. The people who get somewhere are simply the ones who began again one more time than they stopped."],
  /* February: Compassion and Kindness */
  ["Kindness costs the giver almost nothing and is often the largest thing that happens to the person who receives it. You will rarely know which of your small decencies was the one that mattered. Give them all.",
   "Be gentle with the tired, the slow and the rude; you have been each of them. A soft word to someone having a hard day is the one part of your shift that will still be true in a year.",
   "Compassion begins at home, with the one person you are hardest on. Speak to yourself this morning the way you would speak to a friend who had done exactly what you did yesterday."],
  /* March: Discipline and Habit */
  ["Discipline is not a mood; it is a decision made once, so that you do not have to make it every day. Decide the hour, the place and the first move, and let the habit carry what willpower cannot.",
   "You do not rise to the level of your goals. You fall to the level of what you actually do on an ordinary Tuesday. Build the ordinary Tuesday and the goals will look after themselves.",
   "Small, kept promises are the strongest material there is. A promise to yourself, kept for a week, becomes a fact about who you are. Keep a tiny one today."],
  /* April: Renewal and the Way */
  ["Water does not fight the rock; it goes around, and in time the rock is a pebble. There is a way through the day that does not require force. Look for it before you push.",
   "Growth is not loud. The tree does not announce the ring it adds this year. Trust the quiet work you are doing on the days when nothing seems to change.",
   "Let go of the version of today you planned and meet the one that arrived. Renewal is not going back to what was; it is becoming ready for what is."],
  /* May: Wisdom and Counsel */
  ["Wisdom is knowing which of your thoughts to take seriously. Most of them are weather. Let the weather pass and act on the one that is still there when the sky clears.",
   "Ask the person who has done it. Pride keeps more people stuck than ignorance ever did. A good question, asked early, is the cheapest thing you will ever buy.",
   "Old sayings survive because they are load-bearing. Choose one this month and carry it into a real situation; a proverb that has been tested once is yours for life."],
  /* June: Truth and Clarity */
  ["Say the true thing plainly and early. A clear no is a kindness; a fuzzy yes is a debt. Most of the trouble in a week comes from the sentences people did not say on Monday.",
   "Clarity is a discipline of subtraction. Take away what you are not sure of, what you added to sound better, what you hoped was true. What remains is smaller and can be stood on.",
   "Be honest about where you are. You cannot navigate from where you wish you were. The map only works once you have marked the dot truthfully."],
  /* July: Courage in Trial */
  ["Courage is not the absence of fear; it is doing the next right thing with your hands shaking. Nobody who did anything worth doing waited to feel brave first.",
   "The obstacle in front of you is also the training. Every hard shift, every hard conversation, is building exactly the strength you will need for the one after it.",
   "You have survived every bad day you have ever had. That record is unbroken. Whatever today holds, you bring that whole record with you."],
  /* August: Impermanence */
  ["This will pass. The good parts too, which is why you should look at them properly while they are here. Nothing is being taken from you; everything is being lent.",
   "Because it ends, it matters. The shift, the season, the summer, the life. Impermanence is not the sad news; it is what gives an ordinary morning its weight.",
   "Hold things lightly. A grip that is too tight breaks what it holds and tires the hand. Care completely, and let go on time."],
  /* September: Justice and Service */
  ["Service is not servility. To make someone comfortable, fed and seen is one of the oldest and most honourable kinds of work there is. Do it as if it were beneath no one, because it is not.",
   "Fairness starts with the people nobody is watching you treat. How you speak to the dishwasher, the driver, the new hire on their first day, is the truest measure of your character.",
   "Leave every room a little better than you found it. Not dramatically; a chair pushed in, a name remembered, a debt repaid. Justice is mostly made of small, kept accounts."],
  /* October: Stillness and Silence */
  ["You do not have to fill every silence. Some of the best things you will ever say are the sentences you decided not to. Let a quiet moment stay quiet and see what arrives in it.",
   "Sit until the water clears. The mud is not the problem; stirring is. Ten still minutes will show you the bottom of a question that an hour of worrying kept murky.",
   "Stillness is a skill, not a gift. Practise it in small doses: the red light, the queue, the minute before the doors open. The mind you bring to the rush is the mind you trained in the pause."],
  /* November: Gratitude and Mortality */
  ["Count something this morning. The people who are still here, the body that got you out of bed, the roof. Gratitude is not pretending things are fine; it is refusing to let the good go unrecorded.",
   "Number your days, not to be gloomy, but to be accurate. A life is a finite number of mornings, and knowing that is what turns an ordinary one into a chance.",
   "Thank someone today who does not expect it. The words cost you ten seconds and may be repeated by them for years. Gratitude spoken aloud is the one investment that never falls."],
  /* December: Renewal and Hope */
  ["The dark comes early now, and it will turn. It always has. Hope is not a feeling you wait for; it is the decision to act as if the light is coming, because it is.",
   "You can begin the year today. The calendar is a convention; the resolve is yours. Whatever you were going to start in January, start the smallest piece of it this morning.",
   "Look back only long enough to be kind to the person who lived this year. Then face forward. The seasons turn, and so can you; that is the oldest promise there is."]
];
