/* First Light: canon structure and verse pools
   Extracted verbatim from first_light_year_4.html.
   Declares globals; loaded by a classic <script> tag. */

const BIBLE_BOOKS=[["Genesis",50],["Exodus",40],["Leviticus",27],["Numbers",36],["Deuteronomy",34],["Joshua",24],["Judges",21],["Ruth",4],["1 Samuel",31],["2 Samuel",24],["1 Kings",22],["2 Kings",25],["1 Chronicles",29],["2 Chronicles",36],["Ezra",10],["Nehemiah",13],["Esther",10],["Job",42],["Psalms",150],["Proverbs",31],["Ecclesiastes",12],["Song of Songs",8],["Isaiah",66],["Jeremiah",52],["Lamentations",5],["Ezekiel",48],["Daniel",12],["Hosea",14],["Joel",3],["Amos",9],["Obadiah",1],["Jonah",4],["Micah",7],["Nahum",3],["Habakkuk",3],["Zephaniah",3],["Haggai",2],["Zechariah",14],["Malachi",4],["Matthew",28],["Mark",16],["Luke",24],["John",21],["Acts",28],["Romans",16],["1 Corinthians",16],["2 Corinthians",13],["Galatians",6],["Ephesians",6],["Philippians",4],["Colossians",4],["1 Thessalonians",5],["2 Thessalonians",3],["1 Timothy",6],["2 Timothy",4],["Titus",3],["Philemon",1],["Hebrews",13],["James",5],["1 Peter",5],["2 Peter",3],["1 John",5],["2 John",1],["3 John",1],["Jude",1],["Revelation",22]];

const TANAKH_BOOKS=[["Genesis",50],["Exodus",40],["Leviticus",27],["Numbers",36],["Deuteronomy",34],["Joshua",24],["Judges",21],["Samuel",55],["Kings",47],["Isaiah",66],["Jeremiah",52],["Ezekiel",48],["The Twelve",67],["Psalms",150],["Proverbs",31],["Job",42],["Song of Songs",8],["Ruth",4],["Lamentations",5],["Ecclesiastes",12],["Esther",10],["Daniel",12],["Ezra–Nehemiah",23],["Chronicles",65]];

const JUZ=[ "al-Fatiha 1","al-Baqarah 142","al-Baqarah 253","Al 'Imran 93","an-Nisa 24","an-Nisa 148","al-Ma'idah 82","al-An'am 111","al-A'raf 88","al-Anfal 41","at-Tawbah 93","Hud 6","Yusuf 53","al-Hijr 1","al-Isra 1","al-Kahf 75","al-Anbiya 1","al-Mu'minun 1","al-Furqan 21","an-Naml 56","al-'Ankabut 46","al-Ahzab 31","Ya-Sin 28","az-Zumar 32","Fussilat 47","al-Ahqaf 1","adh-Dhariyat 31","al-Mujadilah 1","al-Mulk 1","an-Naba 1"];

const SURAH_AYAHS=[7,286,200,176,120,165,206,75,129,109,123,111,43,52,99,128,111,110,98,135,112,78,118,64,77,227,93,88,69,60,34,30,73,54,45,83,182,88,75,85,54,53,89,59,37,35,38,29,18,45,60,49,62,55,78,96,29,22,24,13,14,11,11,18,12,12,30,52,52,44,28,28,20,56,40,31,50,40,46,42,29,19,36,25,22,17,19,26,30,20,15,21,11,8,8,19,5,8,8,11,11,8,3,9,5,4,7,3,6,3,5,4,5,6];

const JUZ_START=[[1,1],[2,142],[2,253],[3,93],[4,24],[4,148],[5,82],[6,111],[7,88],[8,41],[9,93],[11,6],[12,53],[15,1],[17,1],[18,75],[21,1],[23,1],[25,21],[27,56],[29,46],[33,31],[36,28],[39,32],[41,47],[46,1],[51,31],[58,1],[67,1],[78,1]];

const DHP_CH=[["The Twin Verses",20],["Heedfulness",32],["The Mind",43],["Flowers",59],["The Fool",75],["The Wise",89],["The Arahant",99],["The Thousands",115],["Evil",128],["The Rod",145],["Old Age",156],["The Self",166],["The World",178],["The Buddha",196],["Happiness",208],["Affection",220],["Anger",234],["Impurity",255],["The Just",272],["The Path",289],["Miscellaneous",305],["Hell",319],["The Elephant",333],["Craving",359],["The Monk",382],["The Brahmana",423]];

const RV_MANDALAS=[191,43,62,58,87,75,104,103,114,191];

const POOLS={
bible:[
["In the beginning was the Word, and the Word was with God, and the Word was God.","John 1:1"],
["Blessed are the pure in heart, for they shall see God.","Matthew 5:8"],
["Love is patient and kind; love does not envy or boast.","1 Corinthians 13:4"],
["Nothing will be able to separate us from the love of God in Christ Jesus our Lord.","Romans 8:39"],
["You shall love the Lord your God with all your heart, soul, and mind.","Matthew 22:37"],
["Do not be anxious about anything, but in everything by prayer let your requests be made known to God.","Philippians 4:6"],
["Come to me, all who labor and are heavy laden, and I will give you rest.","Matthew 11:28"],
["I am the way, and the truth, and the life.","John 14:6"],
["Ask, and it will be given to you; seek, and you will find; knock, and it will be opened.","Matthew 7:7"],
["The Lord is my shepherd; I shall not want.","Psalm 23:1"],
["Be transformed by the renewal of your mind.","Romans 12:2"],
["We walk by faith, not by sight.","2 Corinthians 5:7"],
["If God is for us, who can be against us?","Romans 8:31"],
["Let your light shine before others, that they may see your good works.","Matthew 5:16"],
["Faith is the assurance of things hoped for, the conviction of things not seen.","Hebrews 11:1"],
["The fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control.","Galatians 5:22–23"],
["Do not let the sun go down on your anger.","Ephesians 4:26"],
["I can do all things through him who strengthens me.","Philippians 4:13"],
["Judge not, that you be not judged.","Matthew 7:1"],
["Blessed are the peacemakers, for they shall be called sons of God.","Matthew 5:9"],
["For where your treasure is, there your heart will be also.","Matthew 6:21"],
["Bear one another's burdens, and so fulfill the law of Christ.","Galatians 6:2"],
["Rejoice always, pray without ceasing, give thanks in all circumstances.","1 Thessalonians 5:16–18"],
["The truth will set you free.","John 8:32"],
["Whatever you did for one of the least of these, you did for me.","Matthew 25:40"],
["Be doers of the word, and not hearers only.","James 1:22"],
["Perfect love casts out fear.","1 John 4:18"],
["Let all that you do be done in love.","1 Corinthians 16:14"],
["My grace is sufficient for you, for my power is made perfect in weakness.","2 Corinthians 12:9"],
["Behold, I make all things new.","Revelation 21:5"],
["In the world you will have tribulation. But take heart; I have overcome the world.","John 16:33"]],
quran:[
["In the name of God, the Most Gracious, the Most Merciful.","Al-Fatiha 1:1"],
["You alone we worship, and You alone we ask for help.","Al-Fatiha 1:5"],
["God, there is no deity except Him, the Ever-Living, the Sustainer of existence.","Ayat al-Kursi 2:255"],
["For indeed, with hardship comes ease.","Ash-Sharh 94:5"],
["So remember Me; I will remember you.","Al-Baqarah 2:152"],
["Indeed, God is with the patient.","Al-Baqarah 2:153"],
["God does not burden a soul beyond that it can bear.","Al-Baqarah 2:286"],
["Say: O God, Owner of Sovereignty, You give sovereignty to whom You will.","Al 'Imran 3:26"],
["And it is by the mercy of God that you were gentle with them.","Al 'Imran 3:159"],
["Indeed, God commands justice, the doing of good, and generosity to kin.","An-Nahl 16:90"],
["And lower to parents the wing of humility out of mercy.","Al-Isra 17:24"],
["And say: My Lord, increase me in knowledge.","Ta-Ha 20:114"],
["The servants of the Most Merciful are those who walk upon the earth in humility.","Al-Furqan 25:63"],
["And those who strive for Us: We will surely guide them to Our ways.","Al-'Ankabut 29:69"],
["O my son, establish prayer, enjoin what is right, and be patient over what befalls you.","Luqman 31:17"],
["Do not despair of the mercy of God; indeed, God forgives all sins.","Az-Zumar 39:53"],
["Call upon Me; I will respond to you.","Ghafir 40:60"],
["God is Kind to His servants.","Ash-Shura 42:19"],
["Man will have nothing but what he strives for.","An-Najm 53:39"],
["And He is with you wherever you are.","Al-Hadid 57:4"],
["Which of the favors of your Lord will you deny?","Ar-Rahman 55:13"],
["God is the Light of the heavens and the earth, light upon light.","An-Nur 24:35"],
["Whoever puts his trust in God — He is sufficient for him.","At-Talaq 65:3"],
["He who created death and life to test you as to which of you is best in deed.","Al-Mulk 67:2"],
["Remember the name of your Lord and devote yourself to Him completely.","Al-Muzzammil 73:8"],
["He has succeeded who purifies himself, and remembers the name of his Lord, and prays.","Al-A'la 87:14–15"],
["He has succeeded who purifies the soul, and failed who corrupts it.","Ash-Shams 91:9–10"],
["And as for the favor of your Lord, proclaim it.","Ad-Duha 93:11"],
["By time, indeed mankind is in loss — except those who believe and do righteous deeds and counsel one another to truth and patience.","Al-'Asr 103:1–3"],
["Verily, in the remembrance of God do hearts find rest.","Ar-Ra'd 13:28"],
["We created you into peoples and tribes that you may know one another.","Al-Hujurat 49:13"]],
veda:[
["Om. We meditate on the radiant glory of the divine Savitr; may that illumine our understanding.","Gayatri Mantra, Rig Veda 3.62.10"],
["Truth is one; the wise call it by many names.","Rig Veda 1.164.46"],
["Who really knows? Whence was it born, whence came this creation?","Nasadiya Sukta, Rig Veda 10.129"],
["From the unreal lead me to the real; from darkness lead me to light; from death lead me to immortality.","Brihadaranyaka Upanishad 1.3.28"],
["All this, whatever moves in this moving world, is enveloped by the Lord.","Isha Upanishad 1"],
["Tat tvam asi: That thou art.","Chandogya Upanishad 6.8.7"],
["Arise! Awake! Approach the great teachers and learn.","Katha Upanishad 1.3.14"],
["When all desires that dwell in the heart fall away, the mortal becomes immortal.","Katha Upanishad 2.3.14"],
["Truth alone triumphs, not falsehood.","Mundaka Upanishad 3.1.6"],
["Two birds, close companions, cling to the selfsame tree: one eats the sweet fruit; the other looks on without eating.","Mundaka Upanishad 3.1.1"],
["I have known that great Person, radiant as the sun, beyond darkness.","Svetasvatara Upanishad 3.8"],
["That which is not thought by the mind, but by which the mind thinks: know that alone to be Brahman.","Kena Upanishad 1.6"],
["Speak the truth. Practice dharma.","Taittiriya Upanishad 1.11"],
["The knower of Brahman attains the highest.","Taittiriya Upanishad 2.1"],
["From joy all beings are born; by joy they live; into joy they return.","Taittiriya Upanishad 3.6"],
["All this, verily, is Brahman.","Chandogya Upanishad 3.14.1"],
["Aham Brahmasmi — I am Brahman.","Brihadaranyaka Upanishad 1.4.10"],
["Consciousness is Brahman.","Aitareya Upanishad 3.3"],
["Common be your intention, common your hearts, so that all may happily agree.","Rig Veda 10.191"],
["I praise Agni, the priest of the sacrifice, the giver of treasures.","Rig Veda 1.1.1"],
["Dawn has appeared, the daughter of the sky; she wakes every living creature to motion.","Rig Veda 1.113"],
["To what god shall we offer our oblation?","Hiranyagarbha Sukta, Rig Veda 10.121"],
["A thousand heads has the Cosmic Person, a thousand eyes, a thousand feet.","Purusha Sukta, Rig Veda 10.90"],
["The face of truth is covered with a golden disc. Unveil it, that I may see.","Isha Upanishad 15"],
["There the sun shines not, nor moon and stars; by His light all this is lighted.","Katha Upanishad 2.2.15"],
["As rivers flowing to the sea lose name and form, so the knower, freed from name and form, reaches the Person beyond.","Mundaka Upanishad 3.2.8"],
["He shining, everything shines after him.","Svetasvatara Upanishad 6.14"],
["The Self is not born, nor does it die; unborn, eternal, everlasting, ancient.","Katha Upanishad 1.2.18"],
["This Self cannot be attained by instruction, nor by intellect, nor by much learning.","Katha Upanishad 1.2.23"],
["May we hear what is good; may we see what is good.","Vedic invocation"],
["Om — this syllable is all this. Its further explanation: all that is past, present, and future is Om.","Mandukya Upanishad 1"]],
pali:[
["Mind precedes all things; mind is their chief, mind is their maker.","Dhammapada 1"],
["Hatred does not cease by hatred, but only by love; this is the eternal rule.","Dhammapada 5"],
["Heedfulness is the path to the deathless; heedlessness is the path to death.","Dhammapada 21"],
["The mind is hard to check, swift, and flits wherever it will. To control it is good.","Dhammapada 35"],
["As a bee gathers nectar and departs without harming the flower, so let the sage walk through a village.","Dhammapada 49"],
["Like a beautiful flower full of color but without scent are the fine words of one who does not act on them.","Dhammapada 51"],
["Long is the night to the wakeful; long is the road to the weary.","Dhammapada 60"],
["If you find no equal or better on the path of life, walk firmly alone: there is no companionship with fools.","Dhammapada 61"],
["The wise are not shaken by blame or praise, as a solid rock is not shaken by the wind.","Dhammapada 81"],
["Better than a thousand hollow words is one word that brings peace.","Dhammapada 100"],
["Though one should conquer a thousand times a thousand men in battle, he who conquers himself is the greatest of conquerors.","Dhammapada 103"],
["Drop by drop is the water pot filled; the wise man, gathering little by little, fills himself with good.","Dhammapada 122"],
["All tremble at violence; all fear death. Comparing others with oneself, one should neither kill nor cause to kill.","Dhammapada 129"],
["He who, seeking his own happiness, does not harm beings who also desire happiness, will find happiness hereafter.","Dhammapada 132"],
["Not by matted hair, nor by lineage, nor by birth is one a brahmana, but by truth and righteousness.","Dhammapada 393"],
["Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.","Dhammapada 204"],
["There is no fire like passion, no grip like hatred, no net like delusion, no river like craving.","Dhammapada 251"],
["You yourselves must strive; the Buddhas only point the way.","Dhammapada 276"],
["All conditioned things are impermanent: when one sees this with wisdom, one turns away from suffering.","Dhammapada 277"],
["To avoid all evil, to cultivate good, and to purify one's mind: this is the teaching of the Buddhas.","Dhammapada 183"],
["The gift of the Dhamma excels all gifts.","Dhammapada 354"],
["Irrigators channel waters; fletchers straighten arrows; carpenters shape wood; the wise master themselves.","Dhammapada 80"],
["As a mother would protect her only child with her life, so cultivate a boundless heart toward all beings.","Karaniya Metta Sutta"],
["Now this, monks, is the noble truth of suffering, and this is the path leading to its cessation.","Dhammacakkappavattana Sutta, SN 56.11"],
["Do not go by hearsay, by scripture, by logic alone, but when you know for yourselves these things are wholesome, engage in them.","Kalama Sutta, AN 3.65"],
["All conditioned things are subject to decay. Strive on with diligence.","Mahaparinibbana Sutta, DN 16"],
["These are the roots of trees; these are empty huts. Meditate; do not be negligent.","Majjhima Nikaya refrain"],
["Just as the great ocean has one taste, the taste of salt, so this Dhamma has one taste: the taste of freedom.","Udana 5.5"],
["Mindfulness of the body leads to the deathless.","Anguttara Nikaya 1"],
["Speak the truth; do not yield to anger; give, even if only a little, when asked.","Dhammapada 224"],
["Let one be devoted to heedfulness; guard your own mind as a fortress.","Dhammapada 315, rendered"]],
tanakh:[
["Hear, O Israel: the Lord our God, the Lord is one.","Deuteronomy 6:4"],
["In the beginning God created the heavens and the earth.","Genesis 1:1"],
["Do justly, love mercy, and walk humbly with your God.","Micah 6:8"],
["Be still, and know that I am God.","Psalm 46:10"],
["The Lord is my shepherd; I shall not want.","Psalm 23:1"],
["I will lift up my eyes to the mountains: from where shall my help come?","Psalm 121:1"],
["They shall beat their swords into plowshares.","Isaiah 2:4"],
["To every thing there is a season, and a time to every purpose under heaven.","Ecclesiastes 3:1"],
["Justice, justice shall you pursue.","Deuteronomy 16:20"],
["Let justice roll down like waters, and righteousness like an ever-flowing stream.","Amos 5:24"],
["If I am not for myself, who will be for me? If not now, when?","Hillel, Pirkei Avot 1:14"],
["This is the day that the Lord has made; let us rejoice and be glad in it.","Psalm 118:24"],
["Your word is a lamp to my feet and a light to my path.","Psalm 119:105"],
["Trust in the Lord with all your heart.","Proverbs 3:5"],
["The fear of the Lord is the beginning of wisdom.","Proverbs 9:10"],
["Teach us to number our days, that we may get a heart of wisdom.","Psalm 90:12"],
["Those who wait for the Lord shall renew their strength; they shall mount up with wings like eagles.","Isaiah 40:31"],
["Behold, how good and pleasant it is when brothers dwell in unity.","Psalm 133:1"],
["The heavens declare the glory of God, and the sky proclaims his handiwork.","Psalm 19:1"],
["I have set before you life and death, blessing and curse. Therefore choose life.","Deuteronomy 30:19"],
["The Lord bless you and keep you; the Lord make his face shine upon you.","Numbers 6:24–25"],
["Cast your burden on the Lord, and he will sustain you.","Psalm 55:22"],
["Weeping may tarry for the night, but joy comes with the morning.","Psalm 30:5"],
["Create in me a clean heart, O God, and renew a right spirit within me.","Psalm 51:10"],
["Remember the Sabbath day, to keep it holy.","Exodus 20:8"],
["You shall love your neighbor as yourself: I am the Lord.","Leviticus 19:18"],
["Return to me, and I will return to you, says the Lord of hosts.","Malachi 3:7"],
["The world stands on three things: on Torah, on service, and on deeds of loving-kindness.","Pirkei Avot 1:2"],
["It is not incumbent upon you to complete the work, but neither are you free to desist from it.","Pirkei Avot 2:16"],
["For everything there is a season — a time to weep, and a time to laugh.","Ecclesiastes 3:1,4"],
["Arise, shine, for your light has come.","Isaiah 60:1"]]
};
