/* First Light: the almanac calendar and the Readings.

   Two things live here. The almanac's day-of-year table, which every dated
   view uses; and the Readings, the ten works divided into days by
   js/data-plans.js (generated by .scripts/plans/build-plans.js, held to its
   rules by .scripts/check-plans.js).

   --- THE DAY-OF-YEAR RULE ---
   The artifact computed the day of the year two different ways. `doyOf()` used a
   fixed table with February pinned at 29; `renderToday()` used the real calendar.
   In a common year these disagree by one from March onward, so the rotating
   reflection drifted out of step for ten months.

   This file settles it: the fixed 366-slot table is the only one, and every
   caller uses it.

   That is a deliberate choice, not a convenience. The almanac is dated: the
   first of January is Seneca every year, and it would be a poor almanac if a
   given date drew a different voice depending on the year. A fixed table keeps
   each date's voice permanent. The cost is that in a common year slot 60 is
   never reached, so the leap-day voice appears once in four years. That is the
   right cost: the artifact's own subtitle promises "366 voices, one for every day
   of the year, including the leap day", and a voice reserved for the twenty-ninth
   of February should be rare.

   The Readings no longer follow this calendar. Day one of a plan is the day
   the reader begins, and a missed morning waits. The old calendar plans (a
   366-day division cut by unit count) are gone from this file; a verbatim copy
   lives in .scripts/plans/legacy.js, and each plan's prior.legacy in
   data-plans.js maps the old day numbers to atoms, so old ticks carry over. */

var MLEN = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];

function doyOf(m, d) {
  var s = 0;
  for (var i = 0; i < m - 1; i++) s += MLEN[i];
  return s + d;
}
function doyToday() {
  /* the shift clock: at 2am a closer is still on the day they are closing */
  var n = flShiftedNow();
  return doyOf(n.getMonth() + 1, n.getDate());
}
/* Inverse, for the year heatmap and for any view that walks slots rather than dates. */
function doyToMD(doy) {
  var m = 0;
  while (m < 12 && doy > MLEN[m]) { doy -= MLEN[m]; m++; }
  return [m + 1, doy];
}
function isLeap(y) { return (y % 4 === 0 && y % 100 !== 0) || y % 400 === 0; }
/* True when this slot has no date in the given year: slot 60 outside a leap year. */
function doySkipped(doy, y) { return doy === 60 && !isLeap(y === undefined ? new Date().getFullYear() : y); }


/* ═══════════════ the ten works ═══════════════
   [id, name, subtitle, description, (unused), epigraph, epigraphSource, blurb, teachings]

   Listed in the Library's shelf order (FL_LIBRARY, build-library.js SHELF),
   which is the least ranked order the app has. Row index 4 once held the
   calendar plan's labels and is kept empty so the row keeps its shape. The
   length each description gives is read from FL_PLANS, so it cannot drift
   from the division; without FL_PLANS the sentence simply ends sooner. */

function hallOver(id, lead) {
  var n = planDays(id);
  return lead + (n ? ', over ' + n + ' days.' : '.');
}

var HALL_YEARS = [
 ['veda', 'The Rig Veda', 'Śruti: That Which Was Heard',
  hallOver('veda', 'All 1,028 hymns of the ten mandalas in order, each day ending with a hymn'), null,
  'Truth is one; the wise call it by many names.', 'Rig Veda 1.164.46',
  'The oldest scriptures still in daily use, carried by voice for three millennia, culminating in the Upanishads.',
  'Ṛta, Brahman and Atman, Yajña, Om, the Four Ends of Life'],
 ['tanakh', 'The Hebrew Bible', 'Tanakh',
  hallOver('tanakh', 'All 929 chapters in the traditional order, Torah, Prophets and Writings'), null,
  'Hear, O Israel: the Lord our God, the Lord is one.', 'Deuteronomy 6:4',
  'Teaching, Prophets, and Writings: a covenant carried in a portable homeland of words.',
  'Brit, Torah as Teaching, Tzedek, Teshuvah, Shabbat'],
 ['upanishads', 'Three Upanishads', 'Isa, Katha and Kena',
  hallOver('upanishads', 'The Isa, Katha and Kena with Paramananda’s commentary, verse by verse'), null,
  'The Self is not to be known through study, nor through the intellect.', 'Katha Upanishad',
  'The end of the Vedas, where ritual gives way to the question of what the Self actually is.',
  'Atman, Brahman, the two selves, death as teacher'],
 ['pali', 'The Dhammapada', 'From the Pali Canon',
  hallOver('pali', 'All 423 verses, one chapter a day'), null,
  'Mind precedes all things; mind is their chief, mind is their maker.', 'Dhammapada 1',
  'The Buddha’s teaching in its most quoted form: short verses on the mind, anger, craving and the discipline of the self.',
  'the Four Noble Truths, the Eightfold Path, the Three Marks, Dependent Origination, the Brahmavihāras'],
 ['analects', 'The Analects', 'Confucius, as his students remembered him',
  hallOver('analects', 'The twenty books in order, saying by saying, a book a day where a book allows'), null,
  'Is it not pleasant to learn with a constant perseverance and application?', 'Analects 1.1',
  'Not a treatise but a record: what Confucius said, to whom, and on what occasion, gathered by the people who heard it.',
  'Ren, Li, the gentleman, filial piety, the rectification of names'],
 ['tao', 'The Tao Te Ching', 'The way, and its power',
  hallOver('tao', 'One short chapter a day'), null,
  'The Tao that can be trodden is not the enduring and unchanging Tao.', 'Tao Te Ching 1',
  'Eighty-one short chapters on yielding, emptiness and the strength of water, and the root text of Taoism.',
  'Wu wei, yielding, the uncarved block, simplicity'],
 ['zhuangzi', 'The Zhuangzi', 'The other Taoist master',
  hallOver('zhuangzi', 'All thirty-three chapters of the strangest and funniest book in the canon, paragraph by paragraph'), null,
  'Once upon a time, I dreamt I was a butterfly.', 'Zhuangzi 2',
  'Parables, jokes and arguments against certainty, from a writer who thought Confucius earnest and the Tao Te Ching too solemn.',
  'Spontaneity, the useless tree, perspective, free and easy wandering'],
 ['gita', 'The Bhagavad Gita', 'Krishna and Arjuna, on the field',
  hallOver('gita', 'The whole dialogue, one chapter a day, in Annie Besant’s verse by verse translation'), null,
  'Thy business is with the action only, never with its fruits.', 'Bhagavad Gita 2.47',
  'A soldier refuses to fight and is answered with the longest argument in Hinduism about duty, action and the self.',
  'Dharma, karma yoga, detachment, the eternal Self'],
 ['bible', 'The Bible', 'The Christian Scriptures',
  hallOver('bible', 'All 1,189 chapters, Genesis to Revelation'), null,
  'In the beginning was the Word, and the Word was with God, and the Word was God.', 'John 1:1',
  'Two testaments, one arc: creation, covenant, incarnation, and the promised restoration of all things.',
  'Incarnation, Grace, Resurrection, the Kingdom of God, Agape'],
 ['quran', 'The Qur’an', 'The Recitation',
  hallOver('quran', 'All 114 surahs in order, each day ending with a surah wherever the length allows'), null,
  'In the name of God, the Most Gracious, the Most Merciful.', 'The Basmala',
  'Revealed over twenty-three years, held whole in living memory by millions.',
  'Tawhid, Prophethood, the Day of Judgement, Rahma, the Straight Path']
];

function hallById(id) {
  for (var i = 0; i < HALL_YEARS.length; i++) if (HALL_YEARS[i][0] === id) return HALL_YEARS[i];
  return null;
}


/* ═══════════════ the Readings: exact days (FL_PLANS) ═══════════════

   js/data-plans.js divides each work into days of about ten minutes, cut
   only at natural boundaries. These functions read it. planDays(id) is a
   plan's length; planCount(id) answers for a plan or a course.

   The record is FL.readings[id] = {start, read: {day: 1}, div, carried,
   rounds}, where id is a plan id or 'course-<tradition>'. FL.canon is read
   (to carry old ticks over) and never written.

   Everything here tolerates FL_PLANS being absent: it answers null, 0 or
   an empty list, and never throws at load. */

function planDef(id) {
  if (typeof FL_PLANS === 'undefined' || !FL_PLANS || !FL_PLANS.plans) return null;
  return FL_PLANS.plans[id] || null;
}
/* The number of days in a plan's current division (0 when unknown). */
function planDays(id) {
  var P = planDef(id);
  return P ? P.days.length / 3 : 0;
}
/* Day d (1-based): its first and last atom and its words, or null. */
function planDay(id, d) {
  var P = planDef(id);
  if (!P || !(d >= 1) || d > P.days.length / 3 || d !== Math.floor(d)) return null;
  var k = (d - 1) * 3;
  return { d: d, a0: P.days[k], a1: P.days[k + 1], w: P.days[k + 2] };
}

/* Where each seg starts, cached against the plan object it was built from. */
var PLAN_SEG_START = {};
function planSegStarts(id, P) {
  var c = PLAN_SEG_START[id];
  if (c && c.def === P) return c.starts;
  var starts = [0];
  for (var i = 0; i < P.seg.length; i++) starts.push(starts[i] + P.seg[i][2]);
  PLAN_SEG_START[id] = { def: P, starts: starts };
  return starts;
}
/* Atom a (0-based) of a plan: which seg it is in (s), where in it (k,
   0-based), the seg's shown name and text part, and the atom's own number
   as the labels print it (n; the Zhuangzi's is the paragraph number, the
   Dhammapada's and the Tao Te Ching's run through the whole work). */
function planAtom(id, a) {
  var P = planDef(id);
  if (!P) return null;
  var st = planSegStarts(id, P);
  if (!(a >= 0) || a >= st[st.length - 1] || a !== Math.floor(a)) return null;
  var lo = 0, hi = P.seg.length - 1;
  while (lo < hi) {
    var mid = (lo + hi + 1) >> 1;
    if (st[mid] <= a) lo = mid; else hi = mid - 1;
  }
  var seg = P.seg[lo], k = a - st[lo];
  var n = k + 1;
  if (P.work === 'zhuangzi') n = k + (seg[3] || 1);
  else if (P.work === 'dhammapada' || P.work === 'tao') n = a + 1;
  return { a: a, s: lo, k: k, n: n, name: seg[0], part: seg[1], count: seg[2], extra: seg[3] };
}

/* The exact passage, in words: "Genesis 1 to 3", "An-Nisa 4:94 to 4:147",
   "Surah 18, Al-Kahf", "Rig Veda 1.1 to 1.9", "Dhammapada 90 to 99, The
   Venerable (Arhat)", "Katha Upanishad 1.2.1 to 1.2.12". Always "to" for a
   range, never a dash. */
function planLabelRange(id, a0, a1) {
  var P = planDef(id);
  if (!P) return '';
  var A = planAtom(id, a0), B = planAtom(id, a1);
  if (!A || !B || a1 < a0) return '';
  var one = a0 === a1, sameSeg = A.s === B.s;
  var wholeA = A.k === 0, wholeB = B.k === B.count - 1;
  var to = function (x, y) { return one ? String(x) : x + ' to ' + y; };
  switch (P.work) {
    case 'bible':
    case 'tanakh':
      var nm = function (X, single) { return (X.name === 'Psalms' && single) ? 'Psalm' : X.name; };
      if (sameSeg) return nm(A, one) + ' ' + to(A.n, B.n);
      return nm(A, true) + ' ' + A.n + ' to ' + nm(B, true) + ' ' + B.n;
    case 'rigveda':
      return 'Rig Veda ' + to((A.s + 1) + '.' + A.n, (B.s + 1) + '.' + B.n);
    case 'quran':
      if (wholeA && wholeB) {
        if (sameSeg) return 'Surah ' + (A.s + 1) + ', ' + A.name;
        return 'Surahs ' + (A.s + 1) + ' to ' + (B.s + 1) + ', ' + A.name + ' to ' + B.name;
      }
      if (sameSeg) return A.name + ' ' + to((A.s + 1) + ':' + A.n, (B.s + 1) + ':' + B.n);
      return A.name + ' ' + (A.s + 1) + ':' + A.n + ' to ' + B.name + ' ' + (B.s + 1) + ':' + B.n;
    case 'dhammapada':
      return 'Dhammapada ' + to(A.n, B.n) + (sameSeg ? ', ' + A.name : '');
    case 'gita-besant':
      return 'Bhagavad Gita ' + to((A.s + 1) + '.' + A.n, (B.s + 1) + '.' + B.n);
    case 'tao':
      return 'Tao Te Ching ' + to(A.n, B.n);
    case 'analects':
      return 'Analects ' + to((A.s + 1) + '.' + A.n, (B.s + 1) + '.' + B.n);
    case 'zhuangzi':
      if (wholeA && wholeB) return 'Zhuangzi ' + (sameSeg ? String(A.s + 1) : (A.s + 1) + ' to ' + (B.s + 1));
      return 'Zhuangzi ' + to((A.s + 1) + '.' + A.n, (B.s + 1) + '.' + B.n);
    case 'upanishads':
      var ref = function (X) { return (X.extra ? X.extra + '.' : '') + X.n; };
      if (A.name === B.name) return A.name + ' ' + to(ref(A), ref(B));
      return A.name + ' ' + ref(A) + ' to ' + B.name + ' ' + ref(B);
  }
  return '';
}
function planDayLabel(id, d) {
  var day = planDay(id, d);
  return day ? planLabelRange(id, day.a0, day.a1) : '';
}

/* --- the reader's record --- */

function planIsCourse(id) { return String(id).indexOf('course-') === 0; }
/* How many days a plan or a course runs. */
function planCount(id) {
  return planIsCourse(id) ? courseDays(String(id).slice(7)).length : planDays(id);
}
function planState(id) {
  if (!FL.readings || typeof FL.readings !== 'object') FL.readings = {};
  var r = FL.readings[id];
  if (!r || typeof r !== 'object') {
    var P = planDef(id);
    r = FL.readings[id] = { start: null, read: {}, div: P ? P.div : null, carried: {}, rounds: [] };
  }
  if (!r.read || typeof r.read !== 'object') r.read = {};
  if (!r.carried || typeof r.carried !== 'object') r.carried = {};
  if (!Array.isArray(r.rounds)) r.rounds = [];
  if (r.start === undefined) r.start = null;
  return r;
}
/* The record as it stands, without creating one: the pages read through
   this, so opening a plan writes nothing to the reader's record. */
function planPeek(id) {
  var r = (typeof FL !== 'undefined' && FL.readings) ? FL.readings[id] : null;
  return (r && typeof r === 'object') ? r : null;
}
function planReadOf(id) {
  var r = planPeek(id);
  return (r && r.read && typeof r.read === 'object') ? r.read : {};
}
/* Today's reading is the first day not yet read: a missed morning waits.
   0 when every day is read. */
function planToday(id) {
  var n = planCount(id), read = planReadOf(id);
  for (var d = 1; d <= n; d++) if (!read[d]) return d;
  return 0;
}
/* Only days 1..N count, whatever else an old record holds. */
function planProgress(id) {
  var n = planCount(id), read = planReadOf(id), done = 0;
  for (var d = 1; d <= n; d++) if (read[d]) done++;
  return { done: done, total: n, pct: n ? Math.round(done / n * 100) : 0 };
}
/* The first mark is the day the reader began. */
function planMarkRead(id, d, on) {
  var r = planState(id);
  if (on === false) delete r.read[d];
  else {
    r.read[d] = 1;
    if (!r.start) r.start = flToday();
  }
  flSave();
}
/* A finished (or abandoned) run goes into rounds and the plan starts over. */
function planBeginAgain(id) {
  var r = planState(id);
  r.rounds.push({ start: r.start, end: flToday(), n: planProgress(id).done });
  r.read = {};
  r.start = null;
  flSave();
}

/* Which days of the current division a set of marked atoms fully covers. */
function planCovered(P, marked) {
  var out = {};
  for (var k = 0, d = 1; k < P.days.length; k += 3, d++) {
    var all = true;
    for (var a = P.days[k]; a <= P.days[k + 1]; a++) if (!marked[a]) { all = false; break; }
    if (all) out[d] = 1;
  }
  return out;
}
/* Mark the atoms that a set of days covered under an earlier division,
   given as flat pairs (day k covers pairs[2k-2]..pairs[2k-1]). */
function planMarkPairs(pairs, days, marked) {
  for (var key in days) {
    if (!Object.prototype.hasOwnProperty.call(days, key) || !days[key]) continue;
    var d = +key;
    if (!(d >= 1) || d !== Math.floor(d) || d * 2 > pairs.length) continue;
    for (var a = pairs[2 * d - 2]; a <= pairs[2 * d - 1]; a++) marked[a] = 1;
  }
  return marked;
}
/* Days read under division div, as days of the current division, for an
   import. A record under the current division (or with none, or a course)
   keeps its day keys; one under an earlier division is converted through
   prior[div]; one under a division this build never had gives null, since
   its day numbers cannot be known to mean anything here. */
function planConvertRead(id, read, div) {
  var P = planDef(id), out = {};
  read = (read && typeof read === 'object') ? read : {};
  if (!P || !div || div === P.div) {
    for (var k in read) {
      if (Object.prototype.hasOwnProperty.call(read, k) && read[k] && /^\d+$/.test(k) && +k >= 1) out[+k] = 1;
    }
    return out;
  }
  var map = P.prior && P.prior[div];
  return map ? planCovered(P, planMarkPairs(map, read, {})) : null;
}

/* Carry a reader's ticks into the current division. Idempotent.
   1. A record kept under an earlier division is converted through
      prior[div]: its days' atoms are marked, and the days of the current
      division that those atoms fully cover are read.
   2. The calendar plan's ticks (FL.canon[id].done, old day numbers; keys
      past the old plan's length are ignored) are mapped through
      prior.legacy. Only days newly covered since the last carry are added,
      so a day the reader unticked stays unticked.
   Returns true when the record changed. Does not save: the caller does. */
function planCarry(id) {
  var P = planDef(id);
  if (!P || typeof FL === 'undefined') return false;
  var canon = (FL.canon && FL.canon[id]) || null;
  if (!(FL.readings && FL.readings[id]) && !canon) return false;
  var r = planState(id);
  var was = JSON.stringify(r);
  var prior = P.prior || {};

  if (r.div !== P.div) {
    var map = r.div && prior[r.div];
    if (map) r.read = planCovered(P, planMarkPairs(map, r.read, {}));
    else {
      /* a division this build does not know: keep only what can still mean a day */
      var kept = {}, n0 = P.days.length / 3;
      for (var k0 in r.read) if (/^\d+$/.test(k0) && +k0 >= 1 && +k0 <= n0 && r.read[k0]) kept[+k0] = 1;
      r.read = kept;
    }
    r.div = P.div;
  }

  var legacy = prior.legacy;
  if (legacy) {
    var oldLen = legacy.length / 2, old = {};
    var done = (canon && canon.done) || {};
    for (var key in done) {
      if (!Object.prototype.hasOwnProperty.call(done, key) || !done[key]) continue;
      if (!/^\d+$/.test(key)) continue;
      var od = +key;
      if (od >= 1 && od <= oldLen) old[od] = 1;
    }
    var before = planCovered(P, planMarkPairs(legacy, r.carried, {}));
    var now = planCovered(P, planMarkPairs(legacy, old, {}));
    /* the calendar belongs to the first read-through, as the start rule
       below says: after begin again its ticks are remembered, not marked */
    if (!r.rounds.length) for (var d in now) if (!before[d]) r.read[d] = 1;
    r.carried = old;
  }
  /* the calendar's start belongs to the first round only: after begin
     again the new round starts on its own first mark */
  if (!r.start && !r.rounds.length && canon && canon.start) r.start = canon.start;
  return JSON.stringify(r) !== was;
}
/* Two devices' carried calendar ticks, joined. A day that only the two
   sets cover together was never offered on either device, so the reader
   cannot have unticked it: it is marked read (first read-through only).
   A day either side had already been offered is left as the reader left
   it. Then carried is the union, so the carry that follows adds nothing
   twice. Does not save. */
function planCarryMerge(id, theirs) {
  var P = planDef(id);
  if (!P || !theirs || typeof theirs !== 'object') return;
  var r = planState(id), both = {}, k;
  for (k in r.carried) if (Object.prototype.hasOwnProperty.call(r.carried, k) && r.carried[k] && /^\d+$/.test(k)) both[+k] = 1;
  for (k in theirs) if (Object.prototype.hasOwnProperty.call(theirs, k) && theirs[k] && /^\d+$/.test(k)) both[+k] = 1;
  var lg = P.prior && P.prior.legacy;
  if (lg && !r.rounds.length) {
    var mine = planCovered(P, planMarkPairs(lg, r.carried, {}));
    var yours = planCovered(P, planMarkPairs(lg, theirs, {}));
    var now = planCovered(P, planMarkPairs(lg, both, {}));
    for (var d in now) if (!mine[d] && !yours[d]) r.read[d] = 1;
  }
  r.carried = both;
}
/* One plan's (or course's) record from a backup, merged into this
   device's. Days read join only within the same read-through: a backup
   that has begun again fewer times than this device holds a round already
   closed here, so its days and start are left out; one that has begun
   again more times replaces the round in progress here. Rounds are a
   union; the carried calendar ticks merge through planCarryMerge. A record
   kept under another division is converted first, and one under a
   division this build never had brings no days. Does not save. */
function planImport(id, theirs) {
  if (!theirs || typeof theirs !== 'object') return;
  var r = planState(id);
  var tRounds = Array.isArray(theirs.rounds) ? theirs.rounds : [];
  var tr = tRounds.length, mr = r.rounds.length;
  if (tr > mr) { r.read = {}; r.start = null; }
  var read = planConvertRead(id, theirs.read, theirs.div);
  if (tr >= mr && read) {
    for (var d in read) if (read[d]) r.read[d] = 1;
    if (theirs.start && (!r.start || theirs.start < r.start)) r.start = theirs.start;
  }
  tRounds.forEach(function (x) {
    if (!x || typeof x !== 'object') return;
    var same = r.rounds.some(function (m) { return m.start === x.start && m.end === x.end && m.n === x.n; });
    if (!same) r.rounds.push(x);
  });
  if (theirs.carried && typeof theirs.carried === 'object') planCarryMerge(id, theirs.carried);
}
/* Every plan, at boot and after an import. Returns how many changed. */
function planCarryAll() {
  if (typeof FL_PLANS === 'undefined' || !FL_PLANS || !FL_PLANS.plans) return 0;
  var n = 0;
  for (var id in FL_PLANS.plans) {
    if (Object.prototype.hasOwnProperty.call(FL_PLANS.plans, id) && planCarry(id)) n++;
  }
  return n;
}

/* --- the tradition courses ---
   A course's days come from the chamber itself (FL_TRADITIONS): its
   concepts, then its practices, then its festivals, so each title and gloss
   has one source. */
function courseDays(tr) {
  if (typeof FL_TRADITIONS === 'undefined' || !FL_TRADITIONS) return [];
  var T = null;
  for (var i = 0; i < FL_TRADITIONS.length; i++) if (FL_TRADITIONS[i].id === tr) { T = FL_TRADITIONS[i]; break; }
  if (!T) return [];
  var out = [];
  ['concepts', 'practices', 'festivals'].forEach(function (sec) {
    (T[sec] || []).forEach(function (e, j) {
      out.push({ d: out.length + 1, sec: sec, i: j, title: e[0],
                 when: e.length > 2 ? e[1] : null, gloss: e[e.length - 1] });
    });
  });
  return out;
}
/* A course is shown only once its whole set has landed and validated. */
function courseReady(tr) {
  if (typeof FL_PLANS === 'undefined' || !FL_PLANS || !FL_PLANS.courses) return false;
  var c = FL_PLANS.courses[tr];
  return !!(c && c.n && c.n === courseDays(tr).length);
}
